export const certEligibilityMap: Record<string, string> = {
  "제한 없음 (연령, 학력, 경력 무관)": "No restrictions (Age, Academic, Experience irrelevant)",
  "제한 없음": "No restrictions",
  "지정 마이스터고 해당 과정 80% 이상 이수자": "Completed 80%+ of designated Meister High School course",
  "만 14세 이상, 비행경력 20시간 이상": "Age 14+, 20+ flight hours experience",
  "지정 교육기관 이수자": "Completed course at designated educational institution",
  "강습교육 이수자 (고교 강습 포함)": "Completed training course (including high school training)",
  "강습교육 이수자 또는 관련 경력자": "Completed training course or relevant experience holder",
  "관련 학과 4년제 졸업(예정)자 또는 동일 분야 실무 4년 이상": "4-year degree (expected) in related field OR 4+ years work experience",
  "관련 학과 전문대 졸업(예정)자 또는 동일 분야 실무 2년 이상": "Associate degree (expected) in related field OR 2+ years work experience",
  "대학 졸업(예정)자 또는 동일 분야 실무 4년 이상": "College graduate (expected) OR 4+ years work experience",
  "사회복지학 학사학위 소지자 이상": "Bachelor degree or higher in Social Welfare",
  "상담학/심리학 관련 분야 학사학위 이상": "Bachelor degree or higher in Counseling / Psychology",
  "대학 졸업자 이상 및 임상심리 관련 수련 1년 이상": "College graduate or higher + 1+ year clinical psychology training",
  "한국소방안전원 강습교육 이수자": "Completed Korea Fire Safety Institute training course",
  "FPSB 지정 정규 교육 이수자": "Completed FPSB designated formal education",
  "만 14세 이상": "Age 14 or older",
  "승선 경력 2년 이상 (조종면허 취득 시 경력 인정)": "2+ years boarding experience (License recognized)",
  "강습 교육 이수자": "Completed training course",
  "보건/위생 관련 학과 전문대 이상 졸업(예정)자": "Associate degree (expected) or higher in Health / Hygiene field",
  "식품학/영양학 전공 대학교/전문대 졸업자 (이수과목 요건 충족)": "Graduate in Food Science/Nutrition (course requirements met)",
  "보건의료정보 관리 관련 학과 졸업(예정)자": "Graduate (expected) in Health Information Management related field",
  "간호조무사 학원 740시간 이론 + 780시간 실습 이수자": "Completed 740 hrs theory + 780 hrs practice at Nursing Assistant institute",
  "요양보호사 교육기관 지정 교육 이수자": "Completed designated Caregiver training course",
  "대학 관련 전공과목 및 실습 이수자": "Completed relevant college courses and practical training"
};

export const certDescMap: Record<string, string> = {
  "전기 설비의 시공, 정비, 운용 및 관련 기기의 유지보수 작업을 수행하는 마이스터고 전기 계열 핵심 필수 자격증입니다.": "Core essential electrical qualification for installation, maintenance, and operation of electrical equipment.",
  "CAD 시스템을 활용해 기계 도면을 규격에 맞게 작성, 검토, 수정하는 정밀 기계 설계 대표 자격증입니다.": "Representative precision mechanical design certification for drafting and editing CAD drawings according to standards.",
  "CNC 밀링 머신 절삭 프로그램을 작성하고 부품을 정밀 가공하는 대표적인 금속 가공 자격입니다.": "Representative metal machining certification for programming CNC milling and precision machining of components.",
  "CNC 선반 머신을 제어하여 회전체 부품을 정밀 가공 및 측정하는 정밀 공작 자격입니다.": "Precision machining certification for controlling CNC lathe machines to process and measure rotary parts.",
  "플랜트 및 생산 자동화 설비의 기계·전기적 고장을 예방하고 보수 정비하는 스마트 팩토리 필수 자격입니다.": "Essential Smart Factory qualification for diagnosing and repairing mechanical and electrical faults in automated equipment.",
  "인화성, 발화성 위험 물질의 안전 관리 및 관련 제조 시설 점검을 담당하는 화공계열 대표 법정 자격입니다.": "Representative statutory qualification for safety management of flammable/reactive hazardous materials and plant inspection.",
  "화학 물질의 정성·정량 분석 및 품질 관리를 위한 화학 실험 및 기기 분석을 수행하는 자격입니다.": "Certification for chemical testing and instrumental analysis for qualitative/quantitative analysis and quality control.",
  "소프트웨어 프로그래밍 언어(C, Java, Python), 데이터베이스 및 알고리즘 기초를 평가하는 IT 자격입니다.": "IT certification evaluating programming languages (C, Java, Python), databases, and basic algorithms.",
  "자동차 엔진, 기관, 샤시, 전기장치 구조를 점검, 진단하고 정비하는 모빌리티 분야 필수 자격입니다.": "Essential mobility certification for inspecting, diagnosing, and repairing automobile engines, chassis, and electronics.",
  "제조 및 물류 현장에서 지게차를 안전하게 조종해 화물을 적재, 하역, 수송하는 대표 취업 우대 자격입니다.": "Representative preferred hiring qualification for safely operating forklift trucks in manufacturing and logistics.",
  "냉동 장치 및 공기조화 설비를 설치, 운전, 정비하는 시설관리 및 설비 분야 필수 자격입니다.": "Essential facility management certification for installing, operating, and maintaining refrigeration and HVAC equipment.",
  "보일러 및 열사용 기기의 에너지 효율 운전과 안전 관리를 담당하는 자격입니다.": "Certification responsible for energy-efficient operation and safety management of boilers and thermal devices.",
  "엘리베이터, 에스컬레이터 등 승강 설비를 시공 및 안전 보수하는 자격입니다.": "Certification for constructing, installing, and maintaining elevator and escalator safety equipment.",
  "아크 용접봉을 이용해 철골 구조물 및 관재를 정밀 용접하는 전통 기술자격입니다.": "Traditional technical certification for precision arc welding of steel structures and piping.",
  "전자 회로의 설계, 부품 조립, 수리 및 측정 테스트 작업을 안전하게 수행하는 자격입니다.": "Certification for safely performing electronic circuit design, component assembly, repair, and testing.",
  "한국사에 대한 체계적 이해와 역사적 사고력을 평가하는 시험으로 공기업 필수 가산점 자격증입니다.": "Test evaluating systematic understanding of Korean history; essential bonus point qualification for public enterprises.",
  "스프레드시트(Excel) 및 데이터베이스(Access) 실무 활용 능력을 평가하는 대표 사무 자동화 자격입니다.": "Representative office automation certification evaluating practical Excel spreadsheet and Access database skills.",
  "사무 행정 문서 작성 및 스프레드시트(Excel) 기초 실무 능력을 평가하는 표준 자격입니다.": "Standard certification evaluating administrative document drafting and basic Excel spreadsheet practical skills.",
  "데이터베이스 구조 이해 및 SQL을 활용하여 데이터를 검색, 조작하는 데이터 전문 자격입니다.": "Data professional qualification evaluating database structure understanding and data manipulation using SQL.",
  "마이스터고 전기 교육과정을 이수하고 평가를 통과하여 취득하는 고급 전기 시공 기술자격입니다.": "Advanced electrical construction qualification obtained by completing and passing Meister High School electrical curriculum.",
  "3D 모델링 및 치수 공학 설계를 검증받아 취득하는 고급 전공 자격입니다.": "Advanced major qualification obtained through evaluation of 3D modeling and dimensional engineering design.",
  "바이오 의약품 배양, 정제 공정을 조작 및 제어하는 바이오 전문 자격입니다.": "Bio specialization qualification for operating and controlling biopharmaceutical culture and purification processes.",
  "항공기 동체, 날개, 구조물에 대한 점검, 정비 및 판금 보수 작업을 수행하는 자격입니다.": "Certification for performing inspection, maintenance, and sheet metal repair on aircraft airframes and structures.",
  "토목 현장에서 굴착기를 조종해 굴착 및 지반 정지작업을 수행하는 자격입니다.": "Qualification for operating excavators for excavation and ground leveling tasks at civil engineering sites.",
  "자체중량 25kg 초과 드론을 비행 조종할 수 있는 드론 최고 등급 조종 자격입니다.": "Top-tier drone pilot qualification for flying drones exceeding 25kg in weight.",
  "고압가스 제조, 저장, 판매, 사용 시설에서 가스 사고 예방 및 설비 안전 관리를 수행하는 법정 안전관리 자격입니다.": "Statutory safety qualification for gas accident prevention and safety management at high-pressure gas facilities.",
  "불활성 가스를 이용해 비철금속 및 특수강 배관, 정밀 부품을 고품질로 용접하는 전문 정밀 용접 자격입니다.": "Specialized precision welding qualification for high-quality TIG welding of non-ferrous metals and special steel pipes.",
  "공기압 및 유압 제어 시스템을 구성하고 자동화 장치의 회로를 설계·보수하는 마이스터고 자동화 계열 핵심 자격입니다.": "Core automation qualification for configuring pneumatic/hydraulic control systems and designing automated circuit boards.",
  "생산 공장의 생산 설비 및 산업 기계의 고장 진단, 정비, 분해 조립 능력을 검증하는 실무 자격입니다.": "Practical qualification validating fault diagnosis, maintenance, and disassembly/assembly skills for plant machinery.",
  "OrCAD 등 전자 CAD 프로그램을 활용하여 회로도 작성 및 PCB(인쇄회로기판)를 설계하는 전문 자격입니다.": "Specialized qualification for drafting circuit diagrams and designing PCBs using electronic CAD tools like OrCAD.",
  "태양광 발전 시스템의 시공, 운용, 유지보수 및 제어 장치 점검을 담당하는 친환경 에너지 자격입니다.": "Eco-friendly energy qualification for construction, operation, maintenance, and control of solar PV power systems.",
  "3D 모델링 데이터를 바탕으로 3D 프린터를 설정, 출력, 후가공하여 제품을 제작하는 첨단 제조 자격입니다.": "Advanced manufacturing qualification for configuring 3D printers, printing, and post-processing based on 3D CAD data.",
  "HTML, CSS, JavaScript 및 그래픽 툴을 사용해 웹사이트의 UI/UX 화면을 구현하는 자격입니다.": "Qualification for implementing web UI/UX interfaces using HTML, CSS, JavaScript, and graphics tools.",
  "포토샵, 일러스트레이터, 인디자인 등을 활용해 출판물, 시각 디자인, 광고 제작물을 기획·제작하는 자격입니다.": "Qualification for planning and producing publications, visual designs, and advertisements using Photoshop, Illustrator, etc.",
  "수질, 대기, 폐기물, 소음진동 분야의 오염 물질 분석 시험과 환경 오염 방지 시설 운전을 담당합니다.": "Responsible for analyzing pollutants in water, air, waste, noise/vibration and operating pollution control facilities.",
  "측량 장비(토탈스테이션, 레벨 등)를 활용해 토목 및 건설 현장의 위치, 거리, 높이를 측정하는 자격입니다.": "Qualification for measuring coordinates, distances, and elevations at construction sites using Total Stations and levels.",
  "토지의 경계, 면적, 좌표 등을 측정하여 지적 도면을 작성하고 지적 정보 시스템을 등록·관리하는 자격입니다.": "Qualification for measuring land boundaries, areas, and coordinates to draft cadastral maps and manage GIS systems.",
  "무선 통신 송수신기, 안테나 및 무선 통신 설비의 조립, 측정, 유지보수 업무를 수행하는 기술자격입니다.": "Technical qualification for assembly, measurement, and maintenance of wireless transmitters, antennas, and communication gear.",
  "정보통신 네트워크 기기 설치, LAN 케이블 포설, 네트워크 설정 및 신호 측정을 담당하는 자격입니다.": "Qualification responsible for installing telecom equipment, laying LAN cables, network setup, and signal testing.",
  "서버 구축, IP 라우팅, 네트워크 보안, 케이블 제작 등 서버 및 네트워크 제어 능력을 평가합니다.": "Evaluates server setup, IP routing, network security, cable crafting, and overall network control skills.",
  "항공기 피스톤 엔진 및 제트 엔진의 분해, 점검, 조립, 성능 시험 작업을 수행하는 정밀 정비 자격입니다.": "Specialized qualification for disassembly, inspection, and maintenance of aircraft piston and jet engines.",
  "자동차 손상 부위의 조색, 퍼티 작업, 프라이머 도포 및 최종 도장 조작을 전문으로 담당하는 자격입니다.": "자동차 손상 부위의 조색, 퍼티 작업, 프라이머 도포 및 최종 도장 조작을 specialized으로 담당하는 qualification.",
  "변형된 자동차의 차체 프레임을 교정하고 판금, 절단, 용접 기법을 통해 복원하는 전문가 자격입니다.": "변형된 자동차의 차체 프레임을 교정하고 판금, 절단, 용접 기법을 통해 복원하는 specialized가 qualification.",
  "CO2 보호 가스를 이용하여 중공업 구조물 및 관재를 신속하고 효율적으로 용접하는 고성능 용접 자격입니다.": "CO2 보호 가스를 이용하여 중공업 구조물 및 관재를 신속하고 효율적으로 용접하는 고성능 용접 qualification.",
  "광산, 토목 현장 및 원자재 적재장에서 로더 장비를 이용해 토사나 자재를 굴착, 적재, 운반하는 자격입니다.": "광산, 토목 현장 및 원자재 적재장에서 로더 장비를 이용해 토사나 자재를 굴착, 적재, 운반하는 qualification.",
  "도로 포장 및 토목 공사 현장에서 로드롤러 등을 운전해 다짐 작업을 수행하는 자격입니다.": "도로 포장 및 토목 공사 현장에서 로드롤러 등을 운전해 다짐 작업을 수행하는 qualification.",
  "제철소, 조선소, 대형 공장 내부의 천장크레인을 운전하여 중량 화물을 안전하게 신호·이송하는 자격입니다.": "제철소, 조선소, 대형 공장 내부의 천장크레인을 운전하여 중량 화물을 안전하게 신호·이송하는 qualification.",
  "항만 및 물류 터미널에서 컨테이너 전용 크레인을 조종해 선박 양하 및 적재 작업을 전담합니다.": "항만 및 물류 터미널에서 컨테이너 전용 크레인을 조종해 선박 양하 및 적재 작업을 전담합니다.",
  "정밀 측정 기기(3차원 측정기, 버니어캘리퍼스 등)를 사용하여 정밀 기계 부품의 치수 및 형상 오차를 검사하는 자격입니다.": "정밀 측정 기기(3차원 측정기, 버니어캘리퍼스 등)를 사용하여 정밀 기계 부품의 치수 및 형상 오차를 검사하는 qualification.",
  "컴퓨터 하드웨어 회로 및 논리 회로 구성, 마이크로프로세서 관련 설비를 점검하고 유지보수하는 자격입니다.": "컴퓨터 하드웨어 회로 및 논리 회로 구성, 마이크로프로세서 관련 설비를 점검하고 유지보수하는 qualification.",
  "PLC, 메카트로닉스 센서, 유공압 시스템을 결합하여 공장 자동화 기기를 설치하고 제어하는 전문 자격입니다.": "PLC, 메카트로닉스 센서, 유공압 시스템을 결합하여 공장 자동화 기기를 설치하고 제어하는 specialized qualification.",
  "한국전력공사 배전 전주 및 송배전 가공선로 시공을 전문적으로 담당할 수 있는 현장 자격입니다.": "한국전력공사 배전 전주 및 송배전 가공선로 시공을 specialized적으로 담당할 수 있는 현장 qualification.",
  "특정소방대상물의 소방 안전 계획 수립 및 소방 시설 점검을 총괄하는 법정 안전관리 전문 자격입니다.": "특정소방대상물의 소방 안전 계획 수립 및 소방 시설 점검을 총괄하는 법정 안전관리 specialized qualification.",
  "고층 건축물 및 고위험 공장에서 필수 수임하는 소방 법정 최고 수준의 종합 안전 관리 자격입니다.": "고층 건축물 및 고위험 공장에서 essential 수임하는 소방 법정 최고 수준의 종합 안전 관리 qualification.",
  "데이터 기획, R 및 Python을 활용한 빅데이터 탐색과 데이터 분석 기본 역량을 검증합니다.": "데이터 기획, R 및 Python을 활용한 빅데이터 탐색과 데이터 분석 기본 역량 qualification verifying expertise.",
  "리눅스 OS 설치, 기본 명령 관리, 서버 네트워크 구축 실무 능력을 평가하는 자격입니다.": "리눅스 OS 설치, 기본 명령 관리, 서버 네트워크 구축 practical 능력 qualification.",
  "아래한글 프로그램을 활용해 고급 문서 작성, 표 및 차트 편집 실무 능력을 평가합니다.": "아래한글 프로그램을 활용해 advanced 문서 작성, 표 및 차트 편집 practical 능력 qualification.",
  "Excel 프로그램을 이용해 함수, 데이터 분석, 필터링, 피벗 테이블을 처리하는 실무 문서 자격입니다.": "Excel 프로그램을 이용해 함수, 데이터 분석, 필터링, 피벗 테이블을 처리하는 practical 문서 qualification.",
  "PowerPoint를 이용해 프레젠테이션 슬라이드, 애니메이션 및 시각 자료 작성을 평가합니다.": "PowerPoint를 이용해 프레젠테이션 슬라이드, 애니메이션 및 시각 자료 작성 qualification.",
  "한글, 엑셀, 파워포인트 등 주요 OA 과목 중 3개 이상 A등급 취득 시 발급되는 종합 사무 자동화 실무 인증입니다.": "한글, 엑셀, 파워포인트 등 주요 OA 과목 중 3개 이상 A등급 취득 시 발급되는 종합 사무 자동화 practical 인증입니다.",
  "마이크로소프트 오피스 필수 4개 과목(Excel, Word, PowerPoint, Access 등) 합격 시 부여되는 국제 사무 자격입니다.": "마이크로소프트 오피스 essential 4개 과목(Excel, Word, PowerPoint, Access 등) 합격 시 부여되는 국제 사무 qualification.",
  "사무 행정에 필요한 워드프로세서 프로그램의 신속·정확한 편집 능력을 평가하는 표준 사무 자격입니다.": "사무 행정에 필요한 워드프로세서 프로그램의 신속·정확한 편집 능력을 평가하는 표준 사무 qualification.",
  "전산회계 프로그램을 활용하여 회계 정보의 입력, 결산, 부가가치세 실무 처리를 수행하는 회계 대표 자격입니다.": "전산회계 프로그램을 활용하여 회계 정보의 입력, 결산, 부가가치세 practical 처리를 수행하는 회계 representative qualification.",
  "기업 경리 기초 원리 및 전산 회계 프로그램 기초 전표 처리를 평가하는 입문 자격입니다.": "기업 경리 basic 원리 및 전산 회계 프로그램 basic 전표 처리를 평가하는 입문 qualification.",
  "재무회계, 원가회계, 부가가치세, 원천징수 실무를 총괄 처리하는 중급 세무회계 자격입니다.": "재무회계, 원가회계, 부가가치세, 원천징수 practical를 총괄 처리하는 중급 세무회계 qualification.",
  "기업 재무제표 작성 및 ERP 회계 시스템 운영 능력을 검증하는 상공회의소 주관 사무 자격입니다.": "기업 재무제표 작성 및 ERP 회계 시스템 운영 능력을 검증하는 상공회의소 주관 사무 qualification.",
  "회계 원리 기초 및 ERP 전산 회계 프로그램 기초 실무를 평가하는 자격입니다.": "회계 원리 basic 및 ERP 전산 회계 프로그램 basic practical를 평가하는 qualification.",
  "매일경제 주관. 경제 및 경영 분야 기초 비즈니스 사고력을 종합 검증하는 시험입니다.": "매일경제 주관. 경제 및 경영 분야 basic 비즈니스 사고력을 종합 검증하는 examination.",
  "한국경제신문 주관. 복합적 경제 이해력과 시장 구조 판단 능력을 평가하는 시험입니다.": "한국경제신문 주관. 복합적 경제 이해력과 시장 구조 판단 능력을 평가하는 examination.",
  "물류 시스템 기획, 수송, 보관, 하역, 포장 종합 물류 효율화를 관리하는 전문 법정 자격증입니다.": "물류 시스템 기획, 수송, 보관, 하역, 포장 종합 물류 효율화를 관리하는 specialized 법정 certification.",
  "유통 상권 분석, 유통 마케팅, 물류 유통 정보 시스템 운영 역량을 검증하는 자격입니다.": "유통 상권 분석, 유통 마케팅, 물류 유통 정보 시스템 운영 역량을 검증하는 qualification.",
  "무역 서한 작성, 수출입 결제 조건 및 국제 무역 실무 영어 능력을 평가하는 전문 자격입니다.": "무역 서한 작성, 수출입 결제 조건 및 국제 무역 practical 영어 능력을 평가하는 specialized qualification.",
  "올바른 국어 사용 능력과 어휘, 문법, 어문 규정, 사고력을 측정하는 시험입니다.": "올바른 국어 사용 능력과 어휘, 문법, 어문 규정, 사고력을 측정하는 examination.",
  "국어 이해 및 표현 능력을 평가하는 시험으로 주요 공기업 서류 전형에서 우대받습니다.": "국어 이해 및 표현 능력을 평가하는 시험으로 주요 공기업 서류 전형에서 우대받습니다.",
  "글로벌 비즈니스 환경에서의 실정 영어 듣기(LC) 및 읽기(RC) 커뮤니케이션 평가 시험입니다.": "글로벌 비즈니스 환경에서의 실정 영어 듣기(LC) 및 읽기(RC) 커뮤니케이션 평가 examination.",
  "비즈니스 영어 말하기 능력을 평가하는 시험으로 최근 반도체 및 외국계 기업 채용의 핵심 요소입니다.": "비즈니스 영어 말하기 능력을 평가하는 시험으로 최근 반도체 및 외국계 기업 채용의 핵심 요소입니다.",
  "실생활 및 비즈니스 상황에서의 인터뷰형 영어 회화 능력을 자율 응답 방식으로 평가합니다.": "실생활 및 비즈니스 상황에서의 인터뷰형 영어 회화 능력을 자율 응답 방식으로 평가합니다.",
  "일본어 청해 및 독해 실무 커뮤니케이션 능력을 객관식으로 종합 평가하는 시험입니다.": "일본어 청해 및 독해 practical 커뮤니케이션 능력을 객관식으로 종합 평가하는 examination.",
  "중국어 실생활 및 비즈니스 회화·독해·작문 기초 능력을 보증하는 국제 중국어 능력 시험입니다.": "중국어 실생활 및 비즈니스 회화·독해·작문 basic 능력을 보증하는 국제 중국어 능력 examination.",
  "마이스터고 전기과 지정 교육과정을 이수한 후 내·외부 평가를 거쳐 취득하는 고급 전기 전문 자격입니다.": "Meister High School 전기과 지정 교육과정을 이수한 후 내·외부 평가를 거쳐 취득하는 advanced 전기 specialized qualification.",
  "마이스터고 전자기술 체계 교육을 통해 재학 중 취득 가능한 고급 전자회로 제어 자격입니다.": "Meister High School 전자기술 체계 교육을 통해 재학 중 취득 가능한 advanced 전자회로 제어 qualification.",
  "3D CAD/CAM 프로그램을 활용한 정밀 부품 가공 과정을 이수하고 합격하여 취득하는 자격입니다.": "3D CAD/CAM 프로그램을 활용한 정밀 부품 가공 과정을 이수하고 합격하여 취득하는 qualification.",
  "자동화 라인 PLC, 로봇 제어, 제어반 제작 기술 역량을 정밀 평가받아 취득하는 자격입니다.": "자동화 라인 PLC, 로봇 제어, 제어반 제작 기술 역량을 정밀 평가받아 취득하는 qualification.",
  "산업 설비 진단, 유공압 제어, 기계 수리 보수 교육과정을 완수한 고교생이 취득하는 고급 자격입니다.": "산업 설비 진단, 유공압 제어, 기계 수리 보수 교육과정을 완수한 고교생이 취득하는 advanced qualification.",
  "최신 모빌리티 전자제어, 엔진 진단, 샤시 정비 실무 과정 이수를 통해 취득하는 자격입니다.": "최신 모빌리티 전자제어, 엔진 진단, 샤시 정비 practical 과정 이수를 통해 취득하는 qualification.",
  "소프트웨어 개발, 데이터베이스 설계 및 네트워크 실무 교육 평가를 거쳐 취득하는 자격입니다.": "소프트웨어 개발, 데이터베이스 설계 및 네트워크 practical 교육 평가를 거쳐 취득하는 qualification.",
  "위험물 제조 및 취급소 안전 관리 실무 교육을 이수한 마이스터고 화공과 학생 필수 자격입니다.": "위험물 제조 및 취급소 안전 관리 practical 교육을 이수한 Meister High School 화공과 학생 essential qualification.",
  "바이오 의약품 유전자 재조합, 배양, 정제 공정을 실무 단위로 이수하여 취득하는 고급 자격입니다.": "바이오 의약품 유전자 재조합, 배양, 정제 공정을 practical 단위로 이수하여 취득하는 advanced qualification.",
  "산업 현장의 중대재해 예방 및 안전 수칙 점검 능력을 검증받는 고급 법정 안전 관리 자격입니다.": "산업 현장의 중대재해 예방 및 안전 수칙 점검 능력을 검증받는 advanced 법정 안전 관리 qualification.",
  "항공기 유공압 장치, 랜딩기어, 환경 제어 계통의 점검 및 정비를 수행하는 자격입니다.": "항공기 유공압 장치, 랜딩기어, 환경 제어 계통의 점검 및 정비를 수행하는 qualification.",
  "항공기의 통신, 계기, 계측 장비, 레이더 등 항공 전자 장비를 수리·점검하는 전문 자격입니다.": "항공기의 통신, 계기, 계측 장비, 레이더 등 항공 전자 장비를 수리·점검하는 specialized qualification.",
  "고속철도(KTX), 지하철, 디젤/전기 기관차의 대차, 동력장치 정비 및 검수를 담당합니다.": "고속철도(KTX), 지하철, 디젤/전기 기관차의 대차, 동력장치 정비 및 검수를 담당합니다.",
  "철도 신호기, 선로 전환기, 자동 궤도 회로 장치 설치 및 전기 신호 유지보수를 전담합니다.": "철도 신호기, 선로 전환기, 자동 궤도 회로 장치 설치 및 전기 신호 유지보수를 전담합니다.",
  "조선소 선박 블록 취부, 구조물 선체 취부 및 선박 건조 가공 실무를 수행하는 자격입니다.": "조선소 선박 블록 취부, 구조물 선체 취부 및 선박 건조 가공 practical를 수행하는 qualification.",
  "플랜트, 건축물 내부의 급배수, 가스, 유체 이송 배관 조립 및 절단·용접 작업을 수행합니다.": "플랜트, 건축물 내부의 급배수, 가스, 유체 이송 배관 조립 및 절단·용접 작업 qualification performing work.",
  "온수 보일러, 난방 배관 및 가스 난방 기기를 안전하게 설치하고 시험 운전하는 자격입니다.": "온수 보일러, 난방 배관 및 가스 난방 기기를 안전하게 설치하고 시험 운전하는 qualification.",
  "농수축산 농가 원료의 가공, 통조림/병조림 제조, 품질 관리 및 식품 위생 모니터링 자격입니다.": "농수축산 농가 원료의 가공, 통조림/병조림 제조, 품질 관리 및 식품 위생 모니터링 qualification.",
  "우수한 작물 종자의 육성, 교잡, 보증, 검인 및 종자 관리 작업을 진행하는 바이오·농업 자격입니다.": "우수한 작물 종자의 육성, 교잡, 보증, 검인 및 종자 관리 작업을 진행하는 바이오·농업 qualification.",
  "버섯 배지 제조, 무균실 균사 접종, 순수 배양 및 종균 관리 실무 능력을 평가받습니다.": "버섯 배지 제조, 무균실 균사 접종, 순수 배양 및 종균 관리 practical 능력을 평가받습니다.",
  "컴퓨터 네트워크 장비 설정, 라우터 및 스위치 명령어 조작, 네트워크 통신 회선 테스트를 전문 수행합니다.": "컴퓨터 네트워크 장비 설정, 라우터 및 스위치 명령어 조작, 네트워크 통신 회선 테스트를 specialized 수행합니다.",
  "소프트웨어 개발, 데이터베이스 구축, 시스템 분석 및 설계를 담당하는 대한민국 대표 IT 종합 자격증입니다.": "소프트웨어 개발, 데이터베이스 구축, 시스템 분석 및 설계를 담당하는 대한민국 representative IT 종합 certification.",
  "전기 설비의 공사, 유지 및 관리, 전기 안전 관리자 선임의 법정 자격을 부여하는 최고 인기의 공학 자격증입니다.": "전기 설비의 공사, 유지 및 관리, 전기 안전 관리자 선임의 법정 자격을 부여하는 최고 인기의 공학 certification.",
  "사업장 내 안전 관리자 선임 요건을 충족하며 산업 재해 예방 및 안전 계획 수립을 전담하는 필수 자격증입니다.": "사업장 내 안전 관리자 선임 요건을 충족하며 산업 재해 예방 및 안전 계획 수립을 전담하는 essential certification.",
  "건설 현장의 특수 안전 사고 예방, 위험성 평가, 안전 교육을 총괄하는 건설 현장 필수 법정 자격증입니다.": "건설 현장의 특수 안전 사고 예방, 위험성 평가, 안전 교육을 총괄하는 건설 현장 essential 법정 certification.",
  "엑셀, 액세스, 파워포인트 등 사무 행정 전산화와 업무 생산성 향상 능력을 검증하는 산업기사 자격입니다.": "엑셀, 액세스, 파워포인트 등 사무 행정 전산화와 업무 생산성 향상 능력을 검증하는 산업기사 qualification.",
  "빅데이터 수집, 저장, 처리, 분석 및 파이썬/R 프로그래밍 기반 데이터 시각화·모델링 능력을 평가합니다.": "빅데이터 수집, 저장, 처리, 분석 및 파이썬/R 프로그래밍 기반 데이터 시각화·모델링 능력 qualification.",
  "데이터 기획, 통계 분석, 데이터 마이닝의 기본 이론과 R 프로그래밍 기초를 평가하는 데이터 자격입니다.": "데이터 기획, 통계 분석, 데이터 마이닝의 기본 이론과 R 프로그래밍 basic를 평가하는 데이터 qualification.",
  "리눅스 OS의 기본 명령어, 시스템 관리, 명령어 인터페이스 실무 운용 능력을 검증합니다.": "리눅스 OS의 기본 명령어, 시스템 관리, 명령어 인터페이스 practical 운용 능력 qualification verifying expertise.",
  "개인정보보호법 및 관계 법령 준수, 사업장 내 개인정보 관리 체계 수립 실무 능력을 인증합니다.": "개인정보보호법 및 관계 법령 준수, 사업장 내 개인정보 관리 체계 수립 practical 능력을 인증합니다.",
  "AWS 가상 아키텍처 설계, 보안, 비용 최적화 및 네트워크 구축 능력을 증명하는 세계 표준 클라우드 자격입니다.": "AWS 가상 아키텍처 설계, 보안, 비용 최적화 및 네트워크 구축 능력을 증명하는 세계 표준 클라우드 qualification.",
  "부가가치세 신고, 원천징수, 연말정산 실무 및 회계 처리 능력을 평가하는 기업 회계 필수 자격입니다.": "부가가치세 신고, 원천징수, 연말정산 practical 및 회계 처리 능력을 평가하는 기업 회계 essential qualification.",
  "법인세 세무조정 및 세무 회계 전체 실무를 총괄하는 회계/세무 자격의 최고 난이도 시험입니다.": "법인세 세무조정 및 세무 회계 전체 practical를 총괄하는 회계/세무 자격의 최고 난이도 examination.",
  "기업 입문용 회계 원리와 기초 회계 전산 프로그램 사용법을 다루는 자격증입니다.": "기업 입문용 회계 원리와 basic 회계 전산 프로그램 사용법을 다루는 certification.",
  "더존 Smart A 프로그램을 활용하여 재무회계 실무를 수행하는 한국공인회계사회 주관 자격입니다.": "더존 Smart A 프로그램을 활용하여 재무회계 practical를 수행하는 한국공인회계사회 주관 qualification.",
  "더존 프로그램을 이용하여 부가가치세 및 원천징수 실무 능력을 검증하는 세무실무 자격증입니다.": "더존 프로그램을 이용하여 부가가치세 및 원천징수 practical 능력을 검증하는 세무practical certification.",
  "ERP 시스템을 통한 전사적 자원 관리 중 회계·재무 모듈 운용 자격을 부여합니다.": "ERP 시스템을 통한 전사적 자원 관리 중 회계·재무 모듈 운용 자격을 부여합니다.",
  "인적 자원 관리, 급여 계산, 사회보험, 근로기준법 관련 ERP 인사 실무 능력을 평가합니다.": "인적 자원 관리, 급여 계산, 사회보험, 근로기준법 관련 ERP 인사 practical 능력 qualification.",
  "구매, 영업, 재고 관리 등 SCM 및 물류 프로세스의 ERP 운용 능력을 다룹니다.": "구매, 영업, 재고 관리 등 SCM 및 물류 프로세스의 ERP 운용 능력 qualification covering practical operations.",
  "생산 계획, 공정 관리, 품질 관리, 외주 관리에 대한 ERP 실무 자격증입니다.": "생산 계획, 공정 관리, 품질 관리, 외주 관리에 대한 ERP practical certification.",
  "무역 실무 지식 및 영문 무역 서한, 계약서 작성, 신용장 해석 능력을 다루는 무역 분야 대표 자격입니다.": "무역 practical 지식 및 영문 무역 서한, 계약서 작성, 신용장 해석 능력을 다루는 무역 분야 representative qualification.",
  "유통 물류 산업의 물류 기획, 마케팅, 매장 관리, 유통 정보 시스템 관리 능력을 검증합니다.": "유통 물류 산업의 물류 기획, 마케팅, 매장 관리, 유통 정보 시스템 관리 능력 qualification verifying expertise.",
  "물류 정책, 물류 하역, 보관 거점 관리, 화물 운송론 등 물류 전반의 종합 관리 능력을 평가하는 최고 국고자격입니다.": "물류 정책, 물류 하역, 보관 거점 관리, 화물 운송론 등 물류 전반의 종합 관리 능력을 평가하는 최고 국고qualification.",
  "FTA 협정별 원산지 판정, 원산지 증명서 발급 및 관세 혜택 증빙 실무를 수행합니다.": "FTA 협정별 원산지 판정, 원산지 증명서 발급 및 관세 혜택 증빙 practical를 수행합니다.",
  "보세창구 및 보세구역에서 통관 물품 화물 관리, 반출입 감시 작업을 수행하는 법정 자격증입니다.": "보세창구 및 보세구역에서 통관 물품 화물 관리, 반출입 감시 작업을 수행하는 법정 certification.",
  "설문조사 기획, 통계 자료 수집, SPSS 활용 통계 데이터 분석 및 보고서 작성을 전담합니다.": "설문조사 기획, 통계 자료 수집, SPSS 활용 통계 데이터 분석 및 보고서 작성을 전담합니다.",
  "구직자 진로 상담, 직업 심리 검사 해석, 취업 알선 및 국비 지원 교육을 안내하는 전문가입니다.": "구직자 진로 상담, 직업 심리 검사 해석, 취업 알선 및 국비 지원 교육을 안내하는 specialized가입니다.",
  "사회복지 정책, 아동/노인/장애인 복지관, 병원 의료사회복지 분야를 총괄하는 보건복지부 자격입니다.": "사회복지 정책, 아동/노인/장애인 복지관, 병원 의료사회복지 분야를 총괄하는 보건복지부 qualification.",
  "청소년의 학업, 고민, 심리 문제를 상담하고 지자체 청소년 상담복지센터에서 활동하는 전문가 자격입니다.": "청소년의 학업, 고민, 심리 문제를 상담하고 지자체 청소년 상담복지센터에서 활동하는 specialized가 qualification.",
  "심리 평가, 심리 검사, 심리 치료 및 정서적 문제 진단을 다루는 병원/센터 임상 자격증입니다.": "심리 평가, 심리 검사, 심리 치료 및 정서적 문제 진단을 다루는 병원/센터 임상 certification.",
  "시설경비, 신변보호, 특수경비 대원을 지도·감독하고 보안 계획을 총괄하는 경찰청 관할 자격입니다.": "시설경비, 신변보호, 특수경비 대원을 지도·감독하고 보안 계획을 총괄하는 경찰청 관할 qualification.",
  "대형 건축물, 특수격리 시설의 소방 계획서 작성 및 소방 시설 관리를 전담하는 법정 자격입니다.": "대형 건축물, 특수격리 시설의 소방 계획서 작성 및 소방 시설 관리를 전담하는 법정 qualification.",
  "중소형 빌딩 및 공동주택의 화재 예방 및 소방 시설 점검 안전관리자로 선임됩니다.": "중소형 빌딩 및 공동주택의 화재 예방 및 소방 시설 점검 안전관리자로 선임됩니다.",
  "아파트 등 공동주택의 운영, 관리비 집행, 건물 유지보수 및 주민 관리를 총괄하는 관리사무소장 자격입니다.": "아파트 등 공동주택의 운영, 관리비 집행, 건물 유지보수 및 주민 관리를 총괄하는 관리사무소장 qualification.",
  "부동산 중개업 개업 및 토지, 건물 매매·임대차 중개 실무를 수행하는 대한민국 국민 대표 자격입니다.": "부동산 중개업 개업 및 토지, 건물 매매·임대차 중개 practical를 수행하는 대한민국 국민 representative qualification.",
  "행정기관 제출 서류 작성, 인가·허가 신청 대행 및 행정 심판 서류 작성을 대행하는 전문 자격증입니다.": "행정기관 제출 서류 작성, 인가·허가 신청 대행 및 행정 심판 서류 작성을 대행하는 specialized certification.",
  "보험 사고 발생 시 손해액 및 보험금을 산정하고 사정하는 보험 금융 핵심 전문가입니다.": "보험 사고 발생 시 손해액 및 보험금을 산정하고 사정하는 보험 금융 핵심 specialized가입니다.",
  "고객의 재무 상태, 투자 상담, 세무 및 은퇴 설계를 컨설팅하는 한국금융연수원 자격입니다.": "고객의 재무 상태, 투자 상담, 세무 및 은퇴 설계를 컨설팅하는 한국금융연수원 qualification.",
  "개인 종합 재무 설계, 세금, 부동산, 은퇴, 상속 설계를 자문하는 금융권 필수 인기 자격증입니다.": "개인 종합 재무 설계, 세금, 부동산, 은퇴, 상속 설계를 자문하는 금융권 essential 인기 certification.",
  "증권 관련 금융투자상품 매매 또는 위탁을 권유하는 증권가 입문용 자격증입니다.": "증권 관련 금융투자상품 매매 또는 위탁을 권유하는 증권가 입문용 certification.",
  "집합투자증권(펀드) 매매 체결 권유 및 상담업무를 담당하는 금융투자협회 자격증입니다.": "집합투자증권(펀드) 매매 체결 권유 및 상담업무를 담당하는 금융투자협회 certification.",
  "고객 만족(CS) 서비스 기획, 고객 응대 프로세스 설계, 고객 클레임 관리 능력을 검증합니다.": "고객 만족(CS) 서비스 기획, 고객 응대 프로세스 설계, 고객 클레임 관리 능력 qualification verifying expertise.",
  "비즈니스 매너, 고객 접점(MOT) 관리, 고객 응대 테크닉을 다루는 서비스 경영 표준 자격입니다.": "비즈니스 매너, 고객 접점(MOT) 관리, 고객 응대 테크닉을 다루는 서비스 경영 표준 qualification.",
  "아웃바운드/인바운드 마케팅, 인비전 시장조사, 고객 관계 관리(CRM) 스킬을 종합 평가합니다.": "아웃바운드/인바운드 마케팅, 인비전 시장조사, 고객 관계 관리(CRM) 스킬을 종합 평가합니다.",
  "국제회의, 전시회, MICE 행사 유치 및 운영 기획, 영문 회의 서신 작성을 담당합니다.": "국제회의, 전시회, MICE 행사 유치 및 운영 기획, 영문 회의 서신 작성 qualification responsible for operations.",
  "전통 한식 조리 위생, 재료 손질 및 30여 가지 실기 지정 메뉴 조리 기술을 검증하는 자격증입니다.": "전통 한식 조리 위생, 재료 손질 및 30여 가지 실기 지정 메뉴 조리 기술을 검증하는 certification.",
  "스프, 스톡, 샐러드, 스테이크 등 서양식 요리 제조 기술 및 조리장 위생 관리를 다룹니다.": "스프, 스톡, 샐러드, 스테이크 등 서양식 요리 제조 기술 및 조리장 위생 관리를 다룹니다.",
  "생선 칼질 및 정밀 회 뜨기, 초밥, 튀김 등 일본식 고급 조리 스킬을 다루는 전문 자격입니다.": "생선 칼질 및 정밀 회 뜨기, 초밥, 튀김 등 일본식 advanced 조리 스킬을 다루는 specialized qualification.",
  "중화 웍 조리, 화력 제어, 튀김 및 볶음 요리 등 중국식 전문 조리 기술을 다룹니다.": "중화 웍 조리, 화력 제어, 튀김 및 볶음 요리 등 중국식 specialized 조리 기술 qualification covering practical operations.",
  "쿠키, 케이크, 파이, 타르트 등 과자류 제품 반죽, 성형, Baking 기술을 체계적으로 검증합니다.": "쿠키, 케이크, 파이, 타르트 등 과자류 제품 반죽, 성형, Baking 기술을 체계적으로 검증합니다.",
  "식빵, 발효빵, 페이스트리 등 효모 발효를 바탕으로 하는 빵류 제조 기술 전문 자격입니다.": "식빵, 발효빵, 페이스트리 등 효모 발효를 바탕으로 하는 빵류 제조 기술 specialized qualification.",
  "헤어 커트, 퍼머넌트, 샴푸, 염색 등 헤어 디자이너로서의 필수 실무 기술 자격을 다룹니다.": "헤어 커트, 퍼머넌트, 샴푸, 염색 등 헤어 디자이너로서의 essential practical 기술 자격 qualification covering practical operations.",
  "얼굴 및 전신 피부 관리, 팩 마스크 착용, 제모 및 위생 관리 능력을 다루는 피부 에스테틱 자격입니다.": "얼굴 및 전신 피부 관리, 팩 마스크 착용, 제모 및 위생 관리 능력을 다루는 피부 에스테틱 qualification.",
  "손톱·발톱 케어, 습식 매니큐어, 젤 네일 아트 및 인조손톱 연장 기술 전문 국가 자격증입니다.": "손톱·발톱 케어, 습식 매니큐어, 젤 네일 아트 및 인조손톱 연장 기술 specialized 국가 certification.",
  "내추럴/웨딩 메이크업, 시대별 메이크업, 무대/속눈썹 연장 및 미용 위생을 평가합니다.": "내추럴/웨딩 메이크업, 시대별 메이크업, 무대/속눈썹 연장 및 미용 위생 qualification.",
  "에스프레소 추출, 우유 스티밍, 스페셜티 커피 제조 및 카페 장비 운용 능력을 평가합니다.": "에스프레소 추출, 우유 스티밍, 스페셜티 커피 제조 및 카페 장비 운용 능력 qualification.",
  "공원, 정원, 도로 녹지공간 조성을 위해 수목 식재, 잔디 시공, 조경 시설물 설치를 수행합니다.": "공원, 정원, 도로 녹지공간 조성을 위해 수목 식재, 잔디 시공, 조경 시설물 설치를 수행합니다.",
  "작물의 우수한 종자 번식, 육종, 종자 감정, 검인 및 보관 실무 기술을 검증합니다.": "작물의 우수한 종자 번식, 육종, 종자 감정, 검인 및 보관 practical 기술 qualification verifying expertise.",
  "느타리, 표고, 팽이버섯 등 버섯 균사 배양 및 종균 접종, 재배사 환경 관리를 수행합니다.": "느타리, 표고, 팽이버섯 등 버섯 균사 배양 및 종균 접종, 재배사 환경 관리를 수행합니다.",
  "생화를 활용한 절화 상품 제작, 꽃바구니, 부케, 공간 화훼 연출 디자인 기술을 다룹니다.": "생화를 활용한 절화 상품 제작, 꽃바구니, 부케, 공간 화훼 연출 디자인 기술 qualification covering practical operations.",
  "가축 사육, 사료 급여, 인공수정 및 축사 위생 환경 관리를 다루는 농축산 필수 자격입니다.": "가축 사육, 사료 급여, 인공수정 및 축사 위생 환경 관리를 다루는 농축산 essential qualification.",
  "체인톱을 이용한 조림, 벌목, 산림 병해충 방제 및 임도 작업 실무 자격을 인증합니다.": "체인톱을 이용한 조림, 벌목, 산림 병해충 방제 및 임도 작업 practical 자격을 인증합니다.",
  "화학합성 물질 없이 천연 자원을 활용하여 유기 농산물을 재배, 생산, 인증하는 자격입니다.": "화학합성 물질 없이 천연 자원을 활용하여 유기 농산물을 재배, 생산, 인증하는 qualification.",
  "급배수, 난방, 가스, 플랜트 배관 설비를 도면에 맞춰 절단, 용접, 이음 및 설치하는 자격입니다.": "급배수, 난방, 가스, 플랜트 배관 설비를 도면에 맞춰 절단, 용접, 이음 및 설치하는 qualification.",
  "건축물 구조체의 벽, 바닥에 타일을 가공하여 접착제로 부착·시공하는 전문 기능자격입니다.": "건축물 구조체의 벽, 바닥에 타일을 가공하여 접착제로 부착·시공하는 specialized 기능qualification.",
  "건축물 지붕, 지하층, 바닥에 아스팔트, 시트, 우레탄 방수재를 도포·시공하는 현장 필수 자격입니다.": "건축물 지붕, 지하층, 바닥에 아스팔트, 시트, 우레탄 방수재를 도포·시공하는 현장 essential qualification.",
  "목재를 활용해 지붕틀, 수구 구조재, 기둥, 내장 목공 가공 및 조립 작업을 다룹니다.": "목재를 활용해 지붕틀, 수구 구조재, 기둥, 내장 목공 가공 및 조립 작업 qualification covering practical operations.",
  "건물 실내 벽면 바탕재를 정돈하고 초배 및 벽지를 재단·재착하여 도배 정마무리를 다룹니다.": "건물 실내 벽면 바탕재를 정돈하고 초배 및 벽지를 재단·재착하여 도배 정마무리를 다룹니다.",
  "시멘트 모르타르, 플라스터 등을 건축물 벽체 및 바닥에 균일하게 바르는 미장 기술을 다룹니다.": "시멘트 모르타르, 플라스터 등을 건축물 벽체 및 바닥에 균일하게 바르는 미장 기술 qualification covering practical operations.",
  "주거용 건물 바닥 온풍/온수 배관을 단열재 위에 배관 조립 시공하는 실무 자격증입니다.": "주거용 건물 바닥 온풍/온수 배관을 단열재 위에 배관 조립 시공하는 practical certification.",
  "건설 공사 현장에서 고소 작업을 지원하기 위한 파이프 가설 비계 구조물을 안전 조립·해체합니다.": "건설 공사 현장에서 고소 작업을 지원하기 위한 파이프 가설 비계 구조물을 안전 조립·해체합니다.",
  "수공구 및 정밀 측정 기기를 사용하여 기계 부품을 가공, 다듬질하여 정확히 조립·맞춤 작업합니다.": "수공구 및 정밀 측정 기기를 사용하여 기계 부품을 가공, 다듬질하여 정확히 조립·맞춤 작업합니다.",
  "플라스틱 수지 제품을 대량 생산하기 위한 사출 금형 장치를 가공, 정밀 조립 및 가공 정비합니다.": "플라스틱 수지 제품을 대량 생산하기 위한 사출 금형 장치를 가공, 정밀 조립 및 가공 정비합니다.",
  "금속 판재 성형용 프레스 금형 부품을 제작하고 조립, 수정 보수 작업을 담당합니다.": "금속 판재 성형용 프레스 금형 부품을 제작하고 조립, 수정 보수 작업 qualification responsible for operations.",
  "금속 재료의 강도, 경도, 기계적 성질을 향상시키기 위한 담금질, 뜨임 등 열처리 가공을 수행합니다.": "금속 재료의 강도, 경도, 기계적 성질을 향상시키기 위한 담금질, 뜨임 등 열처리 가공 qualification performing work.",
  "금속 및 비금속 표면에 도금, 양극 산화 처리, 도장 가공을 통해 부식 방지 및 내구성을 향상시킵니다.": "금속 및 비금속 표면에 도금, 양극 산화 처리, 도장 가공을 통해 부식 방지 및 내구성을 향상시킵니다.",
  "각종 전자 장치의 기판 수리, 회로 검사, 오실로스코프 신호 측정 및 조립 실무를 다룹니다.": "각종 전자 장치의 기판 수리, 회로 검사, 오실로스코프 신호 측정 및 조립 practical를 다룹니다.",
  "하드웨어 논리 회로 설계, 디지털 시스템 인터페이스 제작 및 논리 IC 조립 검사를 다룹니다.": "하드웨어 논리 회로 설계, 디지털 시스템 인터페이스 제작 및 논리 IC 조립 검사를 다룹니다.",
  "공연장, 극장의 무대 음향 설비 조작, 믹싱 콘솔 조작 및 음향 셋업을 총괄하는 국립 문화자격입니다.": "공연장, 극장의 무대 음향 설비 조작, 믹싱 콘솔 조작 및 음향 셋업을 총괄하는 국립 문화qualification.",
  "박물관, 미술관 전시 기획, 유물 및 미술품 수집·보존 전문 자격을 부여하는 문화체육관광부 자격입니다.": "박물관, 미술관 전시 기획, 유물 및 미술품 수집·보존 specialized 자격을 부여하는 문화체육관광부 qualification.",
  "잠수 장비를 착용하고 수중 교량 검사, 수중 용접, 해저 케이블 설치 및 수중 구조 작업을 수행합니다.": "잠수 장비를 착용하고 수중 교량 검사, 수중 용접, 해저 케이블 설치 및 수중 구조 작업 qualification performing work.",
  "어류, 패류, 해조류 등 수산 생물의 번식, 양식장 환경 관리, 수질 측정 및 질병 예방을 다룹니다.": "어류, 패류, 해조류 등 수산 생물의 번식, 양식장 환경 관리, 수질 측정 및 질병 예방 qualification covering practical operations.",
  "engine 5마력 이상의 모터보트, 수상오토바이(제트스키) 등 수상 레저 기구를 자유롭게 조종할 수 있는 해양경찰청 면허입니다.": "engine 5마력 이상의 모터보트, 수상오토바이(제트스키) 등 수상 레저 기구를 자유롭게 조종할 수 있는 해양경찰청 면허입니다.",
  "5톤 이상 25톤 미만의 소형 선박을 항해 조종할 수 있는 해양수산부 해기사 면허 자격입니다.": "5톤 이상 25톤 미만의 소형 선박을 항해 조종할 수 있는 해양수산부 해기사 면허 qualification.",
  "돗을 이용해 세일링하는 요트(Yacht) 레저기구를 조종하기 위해 필수적인 해양경찰청 면허입니다.": "돗을 이용해 세일링하는 요트(Yacht) 레저기구를 조종하기 위해 essential적인 해양경찰청 면허입니다.",
  "아마추어 무선 통신 국을 조작하고 전파 통신 실험 및 비상 무선 통신망을 지원할 수 있습니다.": "아마추어 무선 통신 국을 조작하고 전파 통신 실험 및 비상 무선 통신망을 지원할 수 있습니다.",
  "육상 이동 통신국, 기지국 및 기업 전용 무선망 무선 설비를 법적으로 운영 취급하는 자격입니다.": "육상 이동 통신국, 기지국 및 기업 전용 무선망 무선 설비를 법적으로 운영 취급하는 qualification.",
  "식품 위생, 환경 위생, 감염병 매개 곤충 방제 및 공중위생 관리 업무를 수행하는 보건복지부 자격입니다.": "식품 위생, 환경 위생, 감염병 매개 곤충 방제 및 공중위생 관리 업무를 수행하는 보건복지부 qualification.",
  "병원, 학교, 기업체 단체 급식소에서 영양 계획, 식단 작성, 조리 지도 및 위생 관리를 총괄합니다.": "병원, 학교, 기업체 단체 급식소에서 영양 계획, 식단 작성, 조리 지도 및 위생 관리를 총괄합니다.",
  "환자의 질병 분류, 진료 기록 분석, 의무 기록 정보 관리 및 병원 통계를 전담하는 보건 자격입니다.": "환자의 질병 분류, 진료 기록 분석, 의무 기록 정보 관리 및 병원 통계를 전담하는 보건 qualification.",
  "의사 또는 간호사의 진료를 보조하고 환자의 간호 및 병원 행정 보조업무를 전담하는 보건복지부 자격입니다.": "의사 또는 간호사의 진료를 보조하고 환자의 간호 및 병원 행정 보조업무를 전담하는 보건복지부 qualification.",
  "치매, 중풍 등 노인성 질환으로 거동이 불편한 어르신에게 신체 활동 및 일상생활 지원 서비스를 제공합니다.": "치매, 중풍 등 노인성 질환으로 거동이 불편한 어르신에게 신체 활동 및 일상생활 지원 서비스를 제공합니다.",
  "평생교육 프로그램 기획, 진행, 분석 및 평생학습관 교육 담당자로 활동하는 교육부 자격증입니다.": "평생교육 프로그램 기획, 진행, 분석 및 평생학습관 교육 담당자로 활동하는 교육부 certification.",
  "공문서 작성, 기획서 작성, 어휘력 및 올바른 실용 문장 작성 능력을 종합 채점하는 글쓰기 자격입니다.": "공문서 작성, 기획서 작성, 어휘력 및 올바른 실용 문장 작성 능력을 종합 채점하는 글쓰기 qualification.",
  "문법, 어휘, 창안, 국어 문화 영역의 정확한 사용 능력을 평가하는 공기업/언론사 필수 가산점 자격증입니다.": "문법, 어휘, 창안, 국어 문화 영역의 정확한 사용 능력을 평가하는 공기업/언론사 essential 가산점 certification.",
  "일상 생활 및 글로벌 비즈니스 환경에서의 영어 듣기·읽기 능력을 평가하는 대한민국 표준 공인 어학시험입니다.": "일상 생활 및 글로벌 비즈니스 환경에서의 영어 듣기·읽기 능력을 평가하는 대한민국 표준 공인 어학examination.",
  "비즈니스 회화, 의견 제시, 전화 통화 등 컴퓨터 기반 영어 말하기 능력을 평가하는 어학 평가입니다.": "비즈니스 회화, 의견 제시, 전화 통화 등 컴퓨터 기반 영어 말하기 능력을 평가하는 어학 평가입니다.",
  "실제 인터뷰 방식으로 진행되는 유연하고 실전적인 영어 회화 능력 평가 시험입니다.": "실제 인터뷰 방식으로 진행되는 유연하고 실전적인 영어 회화 능력 평가 examination.",
  "중국어 신문 기사 읽기, 방송 시청 및 자발적 중국어 연설이 가능한 중급 실무 중국어 자격증입니다.": "중국어 신문 기사 읽기, 방송 시청 및 자발적 중국어 연설이 가능한 중급 practical 중국어 certification.",
  "일본어 일상 대화 및 비즈니스 현장에서 유연한 의사소통이 가능한 세계 표준 일본어 능력 시험입니다.": "일본어 일상 대화 및 비즈니스 현장에서 유연한 의사소통이 가능한 세계 표준 일본어 능력 examination.",
  "어도비 포토샵(Adobe Photoshop)을 활용한 정밀 고급 실무 그래픽 및 이미지 보정·편집 능력을 다룹니다.": "어도비 포토샵(Adobe Photoshop)을 활용한 정밀 advanced practical 그래픽 및 이미지 보정·편집 능력 qualification covering practical operations."
};
