

import * as React from 'react';
import { createContext, useState, useEffect } from 'react';

export type Language = 'ko' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (keyOrKo: string, fallbackEn?: string) => string;
}

const koToEnMap: Record<string, string> = {
  '진로': 'Career',
  '마이스터': 'Meister',
  '다이어리': 'Diary',
  '자격증': 'Certificates',
  '직무검사': 'Job Aptitude',
  '기능사': 'Technical Exam',
  '분석': 'analyze',
  '전문성': 'professionalism',
  '독립': 'independence',
  '집중': 'concentration',
  '연구': 'research',
  '소통': 'communication',
  '협력': 'cooperation',
  '팀워크': 'teamwork',
  '리더십': 'leadership',
  '글로벌': 'global',
  '현실': 'reality',
  '현장': 'site',
  '품질': 'quality',
  '실용': 'practical',
  '안전': 'safety',
  '원칙': 'principle',
  '혁신': 'innovation',
  '창의': 'creative',
  '비전': 'vision',
  '도전': 'challenge',
  '미래': 'future',
  '논리': 'logic',
  '기술': 'technology',
  '효율': 'efficiency',
  '합리': 'reasonable',
  '인간미': 'humanity',
  '고객': 'customer',
  '공감': 'empathy',
  '계획': 'plan',
  '체계': 'system',
  '철저': 'thorough',
  '책임': 'responsibility',
  '유연': 'softness',
  '변화': 'change',
  '자율': 'autonomy',
  '적응': 'adaptation',
  '기계': 'machine',
  '설비': 'facility',
  '제조': 'manufacturing',
  '생산': 'production',
  '설계': 'design',
  '개발': 'development',
  '디자인': 'design',
  '독창': 'solo',
  '아이디어': 'idea',
  '서비스': 'service',
  '지원': 'backup',
  '성장': 'growth',
  '열정': 'passion',
  '경쟁력': 'competitiveness',
  '관리': 'management',
  '대기업': 'large company',
  '공공기관': 'public institution',
  '공기업': 'public enterprise',
  '공공': 'public',
  '공사': 'construction',
  '공단': 'satin',
  '한국전력공사 (한전)': 'Korea Electric Power Corporation (KEPCO)',
  '전력자원 개발 및 발전, 송배전': 'Power resource development and generation, transmission and distribution',
  '한국수력원자력 (한수원)': 'Korea Hydro & Nuclear Power (KHNP)',
  '원자력 및 수력 발전': 'nuclear and hydroelectric power',
  '한국철도공사 (코레일)': 'Korea Railroad Corporation (KORAIL)',
  '철도 여객/화물 수송 및 역세권 개발': 'Development of railway passenger/freight transportation and station area',
  '인천국제공항공사': 'Incheon International Airport Corporation',
  '인천국제공항 건설, 관리 및 운영': 'Construction, management and operation of Incheon International Airport',
  '한국도로공사': 'Korea Expressway Corporation',
  '고속도로 건설, 유지관리 및 부대시설': 'Highway construction, maintenance and auxiliary facilities',
  '한국수자원공사 (K-water)': 'Korea Water Resources Corporation (K-water)',
  '수자원의 종합적 개발 및 관리': 'Comprehensive development and management of water resources',
  '한국가스공사': 'Korea Gas Corporation',
  '천연가스 도입, 제조 및 공급': 'Natural gas introduction, manufacturing and supply',
  '한국토지주택공사 (LH)': 'Korea Land and Housing Corporation (LH)',
  '주택 건설, 도시 개발 및 주거 복지': 'Home construction, urban development and housing welfare',
  '한국지역난방공사': 'Korea District Heating Corporation',
  '집단에너지 사업, 지역 냉·난방 공급': 'Integrated energy business, local cooling and heating supply',
  '한전KDN': 'KEPCO KDN',
  '전력 IT, 에너지 ICT 솔루션': 'Power IT, energy ICT solutions',
  '한국남동발전': 'Korea South-East Power Company',
  '화력, 신재생 발전 및 전력 생산': 'Thermal power, renewable power generation and power production',
  '한국환경공단': 'Korea Environment Corporation',
  '환경 오염 방지, 자원순환': 'Prevention of environmental pollution, resource circulation',
  '등록된 주요 사업 정보가 없습니다.': 'There is no major business information registered.',
  '등록된 조직 문화 정보가 없습니다.': 'There is no organizational culture information registered.',
  '등록된 커리어 패스 정보가 없습니다.': 'There is no career path information registered.',
  '등록된 추천 사유가 없습니다.': 'There is no registered reason for recommendation.',
  '기업명 또는 업종 검색...': 'Search for company name or industry...',
  '검색 조건에 일치하는 기업이 없습니다.': 'There are no companies matching your search criteria.',
  '추천 공기업 TOP 10': 'TOP 10 recommended public companies',
  '내 성향과 전공에 맞춘 가장 적합한 공기업/공공기관 리스트입니다.': 'This is a list of public companies/public institutions that are most suitable for my inclination and major.',
  '주요 사업/제품': 'Main business/product',
  '조직 문화': 'organizational culture',
  '핵심 역량 및 가치': 'Core Competencies and Values',
  '우대 전공 & 자격증': 'Preferred Majors & Certifications',
  '연봉 & 복리후생': 'Salary & Benefits',
  '근무 & 채용절차': 'Work & Recruitment Procedure',
  '커리어 패스': 'career path',
  'AI 추천 사유': 'AI Recommendation Reasons',
  '원하시는 정보 카테고리를 선택해주세요': 'Please select the information category you want',
  '상단의 버튼(주요 사업, 조직 문화, 연봉 및 복지, 우대 자격증 등)을 누르면 해당 상세 내용이 표시됩니다.': 'If you click the button at the top (main business, organizational culture, salary and benefits, preferential certification, etc.), the relevant details will be displayed.',
  '주요 사업 및 제품': 'Main business and products',
  '조직 문화 및 근무 분위기': 'Organizational culture and work atmosphere',
  '💡 현직자 리뷰 / 특징 요약': '💡 Current employee review / feature summary',
  '핵심 역량 및 가치 (인재상)': 'Core Competencies and Values ​​(Talent)',
  '우대 전공': 'Preferred major',
  '필요 역량 및 자격증 (하나씩 확인)': 'Required competencies and certifications (check one by one)',
  '마이스터고 출신 평균 연봉 기준': 'Based on average salary for Meister high school graduates',
  '기본급 기준': 'Base salary standard',
  '성과급 및 수당 포함': 'Including performance bonuses and allowances',
  '복리후생 및 복지 제도': 'Welfare benefits and welfare system',
  '근무 지역': 'working area',
  '근무 형태': 'work type',
  '채용 절차': 'Recruitment Process',
  '마이스터고 졸업생 커리어 패스': 'Meister High School Graduate Career Path',
  'MyStair AI 맞춤 추천 사유': 'Reasons for MyStair AI personalized recommendations',
  '공식 채용 및 기업 홈페이지에서 상세 채용 공고를 확인하세요.': 'Check detailed job postings on the official recruitment and company website.',
  '🔗 공식 홈페이지 방문하기': '🔗Visit the official website',
  '나머지 기업 목록': 'Rest of the Companies List',
  '상위 TOP 10 이외의 모든 추천 대기업 및 공기업 리스트입니다. 클릭 시 상세 정보를 볼 수 있습니다.': 'This is a list of all recommended large and public companies other than the top 10. You can view detailed information by clicking.',
  '나만의 기업찾기': 'Find your own company',
  '내 성향과 전공에 딱 맞는 기업 TOP 10': 'TOP 10 companies that perfectly fit my personality and major',
  '나머지 기업 보기': 'See the rest of the companies',
  '프로필 완성': 'Profile completion',
  '사용자님의 프로필을 분석 중입니다...': 'Analyzing your profile...',
  '프로필 정보가 필요합니다': 'We need your profile information',
  '학교, 학과, MBTI, 홀랜드 적성검사': 'School, department, MBTI, Holland Aptitude Test',
  '정보를 먼저 입력해주세요.': 'Please enter your information first.',
  '추천 대기업 TOP 10': 'TOP 10 recommended large companies',
  '내 성향과 전공에 맞춘 가장 적합한 대기업 리스트입니다.': 'This is a list of large companies that are most suitable for my personality and major.',
  '수도전기공업고등학교': 'Sudo Electric Technical High School',
  '서울로봇고등학교': 'Seoul Robot High School',
  '부산기계공업고등학교': 'Busan Mechanical Engineering High School',
  '동아마이스터고등학교': 'Donga Meister High School',
  '금오공업고등학교': 'Geumo Technical High School',
  '미림여자정보과학고등학교': 'Mirim Girls Information Science High School',
  '광주소프트웨어마이스터고등학교': 'Gwangju Software Meister High School',
  '로봇제어과': 'Robot Control Department',
  '전자제어과': 'Electronic Control Department',
  '정밀기계과': 'Precision Machinery Department',
  '소프트웨어과': 'Software Department',
  '전기제어과': 'Electrical Control Department',
  'AI융합과': 'AI Convergence Department',
  '바이오의약과': 'Department of Biomedicine',
  '자동화설비과': 'Automation Equipment Department',
  '삼성전자': 'Samsung Electronics',
  '현대자동차': 'Hyundai Motor Company',
  '한국전력공사': 'Korea Electric Power Corporation',
  'SK하이닉스': 'SK Hynix',
  '한화시스템': 'Hanwha Systems',
  'LG에너지솔루션': 'LG Energy Solution',
  '한국수력원자력': 'Korea Hydro & Nuclear Power',
  'LG디스플레이': 'LG Display',
  '두산에너빌리티': 'Doosan Energy',
  '이미지 크기가 너무 큽니다 (1.5MB 이하만 가능합니다)': 'Image size is too large (only 1.5 MB or less)',
  '프로필 사진': 'profile picture',
  '마이페이지 프로필이 성공적으로 저장되었습니다!': 'My Page profile has been successfully saved!',
  '저장 중 오류가 발생했습니다.': 'An error occurred while saving.',
  '이미 희망 기업에 포함되어 있습니다.': 'It is already included in the desired companies.',
  '희망 기업': 'Desired Companies',
  '보이기': 'Show',
  '숨기기': 'Hide',
  '현재 선택된 희망 기업': 'Currently Selected Desired Companies',
  '나의 성장의 계단 & 진로 프로필': 'Steps of my growth & career profile',
  '전체 편집 모드입니다. 정보를 수정한 후 [전체 저장] 버튼을 눌러주세요.': 'Full edit mode. After editing the information, click the [Save All] button.',
  '저장 완료': 'Save completed',
  '프로필': 'profile',
  '전체 저장': 'Save All',
  '전체 편집 모드': 'Full Edit Mode',
  '이름': 'name',
  '이름 입력': 'Enter your name',
  '고등학교': 'high school',
  '고등학교 선택 또는 입력': 'Select or Enter High School',
  '전공': 'specialty',
  '전공 학과 선택 또는 입력': 'Select or enter major department',
  '예: RC (비워두면 미진단)': 'Example: RC (if left blank, no diagnosis)',
  '홀랜드 코드': 'holland code',
  '목표 기업명 입력 (예: 삼성전자, 한국전력공사)': 'Enter target company name (e.g. Samsung Electronics, Korea Electric Power Corporation)',
  '삭제': 'delete',
  '진로 지도 메모 및 소견을 입력하세요.': 'Enter your career guidance notes and opinions.',
  '소견 저장 완료': 'Findings saved',
  '기업명을 입력하세요 (예: LG에너지솔루션)': 'Enter the company name (e.g. LG Energy Solution)',
  '희망 기업 설정이 저장되었습니다.': 'Your desired company settings have been saved.',
  '한국어': 'korean',
  '사진 변경': 'change photo',
  '마이스터 인재': 'meister talent',
  '수정': 'correction',
  '저장': 'save',
  '전공 학과': 'Major department',
  'MBTI 성격 진단': 'MBTI personality diagnosis',
  '선택 안 함 (미진단)': 'Not selected (undiagnosed)',
  '상세분석': 'Detailed analysis',
  '진단 결과 없음': 'No diagnostic results',
  'MBTI 진단 검사를 진행해보세요': 'Take the MBTI diagnostic test',
  '검사하기': 'inspect',
  '홀랜드 진로 적성': 'Holland Career Aptitude',
  '홀랜드 적성 검사를 진행해보세요': 'Take the Holland Aptitude Test',
  '기업 추가/관리': 'Add/Manage Company',
  '추가': 'addition',
  '설정된 희망 기업이 없습니다.': 'There are no desired companies set.',
  '배경 외계인 설정': 'wallpaper alien settings',
  '우주를 떠다니는 외계인 캐릭터': 'Alien character floating in space',
  '홈페이지(우주 화면) 배경에 귀여운 UFO 외계인 커플들을 표시할지 선택합니다.': 'Choose whether to display cute UFO alien couples on the homepage (space screen) background.',
  '💡 각 박스의 [수정]으로 즉시 변경하거나 [전체 편집 모드]로 상단에서 일괄 수정할 수 있습니다.': '💡 You can change immediately with [Edit] in each box, or batch edit at the top with [Full Edit Mode].',
  '전체 저장 완료': 'Full save completed',
  'MBTI 성격 진단 상세 내역': 'MBTI personality diagnosis details',
  '나의 성격 유형 분석 및 맞춤 직무 가이드': 'My personality type analysis and customized job guide',
  '수동 유형 변경': 'Manual type change',
  '실제 검사 세부지표 비율': 'Proportion of actual inspection detailed indicators',
  '🎯 MBTI 유형별 추천 직무 전체 목록': '🎯 Full list of recommended jobs by MBTI type',
  'MBTI 진단 검사 다시하기': 'Retaking the MBTI Diagnostic Test',
  '홀랜드 직업 적성 검사 상세': 'Holland Vocational Aptitude Test Details',
  'RIASEC 직업적성 유형 분석 및 진로 소견': 'RIASEC occupational aptitude type analysis and career findings',
  '실제 홀랜드 RIASEC 적합도 지표': 'Real Holland RIASEC goodness-of-fit indices',
  '📝 진로 지도 및 적성 종합 소견': '📝 Career guidance and aptitude comprehensive opinion',
  '🎯 맞춤 추천 직무': '🎯 Customized job recommendations',
  '홀랜드 검사 다시하기': 'Test Holland again',
  '희망 기업 (Target Companies) 설정': 'Target Companies Settings',
  '마이스터고 및 직업계고 학생들이 목표로 하는 주요 기업 관리': 'Major corporate management goals for Meister high school and vocational high school students',
  '등록된 기업이 없습니다. 아래의 추천 기업을 클릭하여 추가해 보세요.': 'There are no registered companies. Click to add a recommended company below.',
  '직접 기업 추가하기': 'Add a company manually',
  '💡 인기 마이스터고 추천 목표 기업 (클릭시 바로 추가/삭제)': '💡 Popular Meister High School recommended target companies (click to add/delete immediately)',
  '전기/전자/에너지': 'Electricity/Electronics/Energy',
  '기계/메카/모빌리티': 'Machine/Mecca/Mobility',
  '기계/메카트로닉스': 'Machinery/Mechatronics',
  '모빌리티/자동차/항공': 'Mobility/Automotive/Aviation',
  '화학/바이오/환경': 'Chemistry/Bio/Environment',
  '농림/환경': 'Agriculture/Environment',
  'IT/소프트웨어/OA': 'IT/Software/OA',
  'IT/소프트웨어': 'IT/Software',
  '공통/OA/데이터': 'Common/OA/Data',
  '건설/중장비/안전': 'Construction/Heavy Equipment/Safety',
  '중장비/물류/안전': 'Heavy equipment/logistics/safety',
  '건설/부동산': 'Construction/Real Estate',
  '건설/기계': 'Construction/Machinery',
  '건설/건축': 'Construction/Architecture',
  '공통/어학/사무': 'Common/Language/Office',
  '공통/어학/한국사': 'Common/Language/Korean History',
  '공통/경영/사무': 'Common/Management/Office',
  '공통/어학/무역': 'Common/Language/Trade',
  '공통/어학': 'Common/Language',
  '금융/보험': 'Finance/Insurance',
  '복지/보건': 'Welfare/Health',
  '조리/식품': 'Cooking/Food',
  '미용/패션': 'Beauty/Fashion',
  '자격증 NAVI': 'Certification NAVI',
  '우리가 원하는 자격증을 한눈에!': 'The certifications we want at a glance!',
  '마이스터고 자격증 정밀 검색': 'Meister High School Certification Precise Search',
  '자격증명, 전공 분야, 가산점 적용 기업(삼성, 한전, 코레일 등)을 입력해보세요.': 'Enter your qualifications, field of study, and companies for which additional points apply (Samsung, KEPCO, KORAIL, etc.).',
  '자격증명, 우대기업, 카테고리 검색...': 'Credentials, preferred companies, category search...',
  '전체보기': 'See all',
  '자격증 데이터를 불러오는 중입니다...': 'Loading certification data...',
  ' 데이터를 불러올 수 없습니다.': 'Data could not be loaded.',
  '🔍 검색 조건과 일치하는 자격증이 없습니다.': '🔍 There are no certifications that match your search criteria.',
  '평균 합격률': 'average passing rate',
  '실기 응시료': 'Practical exam fee',
  '자세히 보기 & 접수하기 ➔': 'View Details & Apply ➔',
  '📝 자격증 개요': '📝 Certification Overview',
  '📋 응시 자격 조건': '📋 Eligibility requirements',
  '⭐ 난이도': '⭐ Difficulty',
  '📊 평균 합격률': '📊 Average passing rate',
  '💰 필기 응시료': '💰 Written exam fee',
  '🛠️ 실기 응시료': '🛠️ Practical exam fee',
  '🏢 우대 및 가산점 반영 기업': '🏢 Companies that reflect preferential treatment and additional points',
  '🔗 연계 / 관련 자격증': '🔗 Linkage/Related Certifications',
  '👉 공식 접수 사이트 바로가기': '👉 Go to the official application site',
  '김교범': 'Kyobeom Kim',
  '구미전자공업고등학교 2학년': 'Gumi Electronics Technical High School, 2nd grade',
  '프로젝트 깃허브(GitHub) 레포지토리 관리 및 협업 파이프라인 구축, Mystair 메인페이지 UI/UX 디자인 담당.': 'Responsible for project GitHub repository management and collaboration pipeline construction, and Mystair main page UI/UX design.',
  '박영진': 'Youngjin Park',
  '서비스 백엔드 서버 및 API 통신 설계, 전국 마이스터고 및 기업 취업 데이터 수집·분석 담당.': 'Responsible for service backend server and API communication design, and collection and analysis of employment data from national Meister high schools and companies.',
  '노현우': 'noh hyunwoo',
  '서비스 기획 및 스토리보드 설계, 브랜드 소개를 위한 홍보페이지 UI/UX 디자인 및 인터랙션 담당.': 'Responsible for service planning and storyboard design, promotional page UI/UX design and interaction for brand introduction.',
  '메인으로 돌아가기': 'return to main',
  'Mystair를 만든 사람들': 'The people who created Mystair',
  '구미전자공업고등학교 2학년 주역들이 의기투합하여 기획하고 개발한': 'Planned and developed by the protagonists of the second year of Gumi Electronics Technical High School.',
  '전국 마이스터고 학생 맞춤형 AI 커리어·진로 탐색 플랫폼입니다.': 'This is an AI career and career exploration platform tailored to students at Meister high schools across the country.',
  '마이스터고 학생들의 열정과 기술력으로 제작된 플랫폼입니다. 꿈을 향한 힘찬 첫걸음을 응원합니다.': 'This is a platform created with the passion and technology of Meister High School students. We encourage you to take your first powerful step towards your dream.',
  '🌐 홍보사이트 보기': '🌐 View promotional site',
  '1. 기계나 도구를 다루고 조작하는 활동이 즐겁다.': '1. I enjoy handling and manipulating machines and tools.',
  '2. 손으로 직접 만들거나 수리하는 작업을 선호한다.': '2. I prefer making or repairing things by hand.',
  '3. 야외나 현장에서 직접 몸을 움직이며 일하는 것이 좋다.': '3. It is better to work outdoors or in the field while moving your body.',
  '4. 전기, 전자 장비의 원리를 파악하고 점검하는 데 흥미가 있다.': '4. I am interested in understanding and inspecting the principles of electrical and electronic equipment.',
  '5. 도면이나 기술 설계를 보고 실제 제품을 제작해보고 싶다.': '5. I want to look at drawings or technical designs and create an actual product.',
  '6. 컴퓨터 부품이나 기계 장치를 조립하고 분해하는 것을 잘한다.': '6. Good at assembling and disassembling computer parts and mechanical devices.',
  '7. 눈으로 확인 가능한 실질적인 성과물을 만들어내는 일이 보람차다.': '7. It is rewarding to create tangible results that can be seen with the naked eye.',
  '8. 자동차, 로봇, 공장 설비 등 기술적인 시스템에 관심이 많다.': '8. I am very interested in technical systems such as cars, robots, and factory equipment.',
  '9. 복잡한 이론보다는 직접 실험하고 체험하는 것이 더 잘 맞는다.': '9. Direct experimentation and experience are better suited than complex theories.',
  '10. 안전 수칙을 준수하며 정밀한 작업을 완성해내는 편이다.': '10. I tend to follow safety rules and complete precise work.',
  '11. 과학적 원리나 복잡한 지식을 탐구하는 것이 재미있다.': '11. It is fun to explore scientific principles or complex knowledge.',
  '12. 원인과 결과를 논리적으로 분석하여 문제를 해결하길 즐긴다.': '12. I enjoy solving problems by logically analyzing cause and effect.',
  '13. 새로운 학문이나 전문 정보를 깊이 있게 연구하는 것을 좋아한다.': '13. I like studying new academic subjects or specialized information in depth.',
  '14. 데이터나 통계 자료를 분석하여 패턴을 찾아내는 편이다.': '14. I tend to find patterns by analyzing data or statistical data.',
  '15. 관찰과 실험을 통해 가설을 검증하는 과정에 성취감을 느낀다.': '15. I feel a sense of accomplishment in the process of testing hypotheses through observation and experiment.',
  '16. 수학적, 상징적 개념을 활용하여 문제에 접근하는 편이다.': '16. I tend to approach problems using mathematical and symbolic concepts.',
  '17. 질문이 생기면 정확한 답을 찾을 때까지 파고드는 습관이 있다.': '17. When I have a question, I have a habit of digging into it until I find the exact answer.',
  '18. 새로운 기술 트렌드나 연구 결과에 호기심이 많다.': '18. I am very curious about new technological trends or research results.',
  '19. 독립적으로 집중해서 학술적/기술적 문제를 해결하는 걸 좋아한다.': '19. I like to focus independently and solve academic/technical problems.',
  '20. 비판적이고 객관적인 사고방식으로 상황을 바라본다.': '20. Look at the situation with a critical and objective mindset.',
  '21. 그림, 디자인, 음악 등 창의적인 표현 활동을 좋아한다.': '21. I like creative expression activities such as painting, design, and music.',
  '22. 규격화된 틀보다는 자신의 독창적인 아이디어를 살리는 일을 원한다.': '22. I want to bring my own original ideas to life rather than a standardized framework.',
  '23. 공간, 색상, 미적 감각을 발휘하는 일에 흥미가 있다.': '23. I am interested in using space, color, and aesthetics.',
  '24. 글쓰기, 영상 제작, 미디어 콘텐츠를 만드는 것이 즐겁다.': '24. I enjoy writing, video production, and creating media content.',
  '25. 자유로운 환경에서 상상력을 발휘하여 일하는 것을 선호한다.': '25. I prefer to work imaginatively in a free environment.',
  '26. 감수성이 풍부하며 사물의 아름다움을 잘 포착한다.': '26. Has a lot of sensitivity and is good at capturing the beauty of things.',
  '27. 남들과 똑같은 방식보다는 색다른 개성을 표현하는 편이다.': '27. I tend to express my unique individuality rather than the same way as others.',
  '28. 사용자 경험(UX)이나 인터페이스(UI) 디자인에 관심이 있다.': '28. I am interested in user experience (UX) or interface (UI) design.',
  '29. 직관과 아이디어를 즉흥적으로 결합하여 새로운 것을 만들어낸다.': '29. Create something new by spontaneously combining intuition and ideas.',
  '30. 정형화되지 않은 예술적 작업이나 크리에이티브 업무가 맞는다.': '30. It is suitable for unstructured artistic work or creative work.',
  '31. 다른 사람을 돕고 봉사하거나 상담해주는 일에 보람을 느낀다.': '31. I feel rewarded from helping, volunteering, or counseling others.',
  '32. 새로운 사람들과 쉽게 교류하고 유대감을 형성을 잘한다.': '32. I interact easily with new people and am good at forming bonds.',
  '33. 누군가에게 지식이나 기술을 가르쳐주는 활동이 즐겁다.': '33. I enjoy teaching others knowledge or skills.',
  '34. 타인의 고민이나 감정에 깊이 공감하고 경청해준다.': '34. Deeply empathize with and listen to other people’s concerns and feelings.',
  '35. 팀워크를 이루어 함께 목표를 달성하는 과정을 좋아한다.': '35. I like the process of achieving goals together through teamwork.',
  '36. 대화와 소통을 통해 갈등을 조율하고 해결하는 능력이 있다.': '36. Has the ability to coordinate and resolve conflicts through dialogue and communication.',
  '37. 도움이 필요한 사람들에게 구체적인 조언을 적극 제공한다.': '37. Actively provide specific advice to those in need.',
  '38. 따뜻하고 화기애애한 조직 분위기를 만드는 데 기여한다.': '38. Contribute to creating a warm and friendly organizational atmosphere.',
  '39. 인간관계와 공동체의 안녕 및 성장에 대한 관심이 높다.': '39. There is a high level of interest in the well-being and growth of human relationships and the community.',
  '40. 타인을 서포트하고 육성하는 직무에서 만족감을 느낀다.': '40. I feel satisfied with my job of supporting and nurturing others.',
  '41. 조직이나 프로젝트를 이끌며 리더십을 발휘하는 것을 좋아한다.': '41. I like to demonstrate leadership by leading an organization or project.',
  '42. 목표를 달성하기 위해 사람들을 설득하고 영향력을 행사한다.': '42. Persuade and influence people to achieve goals.',
  '43. 새로운 사업 아이디어나 기획을 제안하고 추진하는 데 흥미가 있다.': '43. I am interested in proposing and pursuing new business ideas or plans.',
  '44. 위험을 무릅쓰더라도 적극적인 도전을 즐기는 편이다.': '44. I tend to enjoy active challenges, even if it means taking risks.',
  '45. 발표나 협상 상황에서 유창하고 논리적으로 말을 잘한다.': '45. Speak fluently and logically in presentation or negotiation situations.',
  '46. 성과 지향적이며 경쟁 상황에서 이기고자 하는 승부욕이 있다.': '46. ​​Is performance-oriented and has the will to win in competitive situations.',
  '47. 자원과 인력을 효율적으로 관리하고 목표를 달성하도록 촉진한다.': '47. Efficiently manage resources and personnel and promote goal achievement.',
  '48. 영업, 마케팅, 비즈니스 전략 분야에서 능력을 발휘하고 싶다.': '48. I want to demonstrate my skills in sales, marketing, and business strategy.',
  '49. 자신감이 넘치고 문제 해결 시 주도적으로 의견을 낸다.': '49. I am confident and take the lead in giving opinions when solving problems.',
  '50. 조직의 비전을 제시하고 구성원들의 동기를 부여하는 데 자신이 있다.': '50. I am confident in presenting the organization’s vision and motivating members.',
  '51. 정해진 규칙과 원칙에 맞춰 체계적으로 일하는 것이 마음 편하다.': '51. I feel comfortable working systematically according to established rules and principles.',
  '52. 자료, 문서, 데이터를 꼼꼼하게 정리하고 기록하는 일을 잘한다.': '52. I am good at organizing and recording materials, documents, and data meticulously.',
  '53. 예산, 숫자, 계산 관련 작업을 정확하게 수행해낸다.': '53. Accurately perform tasks related to budgets, numbers, and calculations.',
  '54. 세부사항을 놓치지 않는 세심함과 정교함이 있다.': '54. There is meticulousness and sophistication that does not miss details.',
  '55. 매뉴얼과 절차를 충실히 준수하며 실수를 줄이려 노력한다.': '55. We faithfully follow manuals and procedures and try to reduce mistakes.',
  '56. 안정적이고 예측 가능한 조직 환경을 선호한다.': '56. I prefer a stable and predictable organizational environment.',
  '57. 일정 관리 및 체크리스트 점검을 철저히 하는 편이다.': '57. I tend to manage schedules and check checklists thoroughly.',
  '58. 행정 업무나 품질 관리, 회계 작업 등에 적성이 맞는다.': '58. Aptitude for administrative work, quality control, accounting work, etc.',
  '59. 정보의 오류를 교정하고 정확도를 확보하는 일을 책임감 있게 수행한다.': '59. We responsibly correct information errors and ensure accuracy.',
  '60. 체계적인 데이터베이스 관리나 표준화 작업에 흥미가 있다.': '60. I am interested in systematic database management or standardization work.',
  '정보가 변경·저장되었습니다.': 'Information has been changed and saved.',
  '진로 지도 및 적성 종합 소견': 'Career guidance and aptitude comprehensive opinion',
  '나만의 맞춤 기업을 추천받기 위해 마이페이지에서': 'Go to My Page to receive recommendations for your own customized company.',
  '주말에는 사람들과 어울리기보다 집에서 쉬는 것이 좋다.': 'I prefer relaxing at home over hanging out with people on weekends.',
  '새로운 사람을 만나는 것을 즐기고 먼저 다가가는 편이다.': 'I enjoy meeting new people and tend to approach them first.',
  '현실적인 사실이나 경험보다는 상상력과 아이디어에 관심이 많다.': 'I am more interested in imagination and ideas than realistic facts or experiences.',
  '일어날 법한 일보다는 실질적으로 일어나는 현실에 더 집중한다.': 'I focus more on what is actually happening in reality than what might happen.',
  '결정을 내릴 때 논리와 객관적인 기준을 중요하게 생각한다.': 'I consider logic and objective criteria important when making decisions.',
  '다른 사람의 감정이나 상황을 먼저 고려하여 결정하는 편이다.': 'I tend to consider others\' feelings or situations first when making decisions.',
  '계획을 미리 세우고 일정에 맞게 행동하는 것을 선호한다.': 'I prefer making plans in advance and acting according to schedule.',
  '그때그때 상황에 맞게 융통성 있게 대처하는 것을 좋아한다.': 'I like responding flexibly to situations as they arise.',
  '다른 사람들의 시선이나 평가에 크게 흔들리지 않는 편이다.': 'I am not easily swayed by others\' opinions or evaluations.',
  '자신의 행동이나 결정에 대해 자주 되돌아보고 걱정하는 편이다.': 'I often reflect on and worry about my actions or decisions.',
  '나는 조용하고 말수가 적은 편이다.': 'I am generally quiet and don\'t talk much.',
  '나는 활발하고 에너지가 넘치는 편이다.': 'I am energetic and active.',
  '나는 눈에 보이는 사실 그대로를 믿는 편이다.': 'I tend to believe what I can see and facts as they are.',
  '나는 숨겨진 의미나 미래의 가능성을 상상하는 것을 좋아한다.': 'I like imagining hidden meanings and future possibilities.',
  '친구가 고민을 이야기할 때 해결책을 먼저 제시하는 편이다.': 'I tend to offer solutions first when a friend talks about their worries.',
  '친구가 고민을 이야기할 때 공감해주고 위로해주는 편이다.': 'I tend to empathize and comfort when a friend talks about their worries.',
  '일을 시작하기 전에 체계적인 계획을 세우는 것이 마음이 편하다.': 'I feel comfortable making systematic plans before starting work.',
  '상황에 따라 유연하게 대처하며 일을 진행하는 것이 좋다.': 'I prefer proceeding flexibly depending on the situation.',
  '스트레스를 받아도 비교적 금방 평온을 되찾는 편이다.': 'I tend to regain calmness relatively quickly even when stressed.',
  '작은 실수에도 오랫동안 마음이 쓰이고 자책하는 경향이 있다.': 'I tend to worry and blame myself for a long time even over small mistakes.',
  '세상의 소금형': 'Salt of the Earth',
  '임금 뒷편의 권력형': 'Power Behind the Throne',
  '예언자형': 'Prophet',
  '과학자형': 'Scientist',
  '백과사전형': 'Encyclopedia',
  '성인군자형': 'Saint',
  '잔다르크형': 'Joan of Arc',
  '아이디어 뱅크형': 'Idea Bank',
  '수완좋은 활동가형': 'Resourceful Activist',
  '사교적인 외교관형': 'Sociable Diplomat',
  '스파크형': 'Spark',
  '발명가형': 'Inventor',
  '사업가형': 'Entrepreneur',
  '친선도모형': 'Goodwill Promoter',
  '언변능숙형': 'Skilled Orator',
  '지도자형': 'Leader',
  '책임감이 강하고 현실적이며 철저한 성격': 'Responsible, realistic, and thorough',
  '차분하고 헌신적이며 책임감 있는 성격': 'Calm, dedicated, and responsible',
  '통찰력 있고 사람들에게 영감을 주는 성격': 'Insightful and inspiring',
  '독창적이고 분석적이며 비전을 제시하는 성격': 'Original, analytical, and visionary',
  '조용하고 관찰력이 뛰어나며 논리적인 성격': 'Quiet, observant, and logical',
  '온화하고 다정하며 현재를 즐기는 성격': 'Gentle, friendly, and enjoying the present',
  '이상적이고 성실하며 내적 신념이 깊은 성격': 'Idealistic, sincere, and deeply principled',
  '호기심 많고 뛰어난 적응력을 가진 성격': 'Curious and highly adaptable',
  '현실적이고 활동적이며 문제 해결에 뛰어난 성격': 'Realistic, active, and good at problem-solving',
  '사교적이고 따뜻하며 사람들을 돕는 성격': 'Sociable, warm, and helpful',
  '열정적이고 창의적이며 새로운 가능성을 탐구하는 성격': 'Passionate, creative, and exploring new possibilities',
  '에너지가 넘치고 지적 도전을 즐기는 성격': 'Energetic and enjoying intellectual challenges',
  '현실적이고 실용적이며 지도력이 있는 성격': 'Realistic, practical, and leadership-oriented',
  '조화롭고 친절하며 책임감이 강한 성격': 'Harmonious, kind, and responsible',
  '카리스마 있고 타인의 성장을 돕는 성격': 'Charismatic and helping others grow',
  '결단력 있고 통솔력이 뛰어나며 비전이 있는 성격': 'Decisive, commanding, and visionary',
  '회계사': 'Accountant',
  '공무원': 'Public Official',
  '데이터 분석가': 'Data Analyst',
  '간호사': 'Nurse',
  '유치원 교사': 'Kindergarten Teacher',
  '상담사': 'Counselor',
  '심리치료사': 'Psychotherapist',
  '작가': 'Writer',
  'HR 디렉터': 'HR Director',
  '시스템 엔지니어': 'Systems Engineer',
  '전략 기획자': 'Strategic Planner',
  '건축가': 'Architect',
  '소프트웨어 개발자': 'Software Developer',
  '기계 공학자': 'Mechanical Engineer',
  '파일럿': 'Pilot',
  '디자이너': 'Designer',
  '예술가': 'Artist',
  '셰프': 'Chef',
  '사회복지사': 'Social Worker',
  '사서': 'Librarian',
  '번역가': 'Translator',
  '수학자': 'Mathematician',
  '프로그래머': 'Programmer',
  '경제학자': 'Economist',
  '경찰관': 'Police Officer',
  '소방관': 'Firefighter',
  '운동선수': 'Athlete',
  '이벤트 플래너': 'Event Planner',
  '승무원': 'Flight Attendant',
  '판매원': 'Salesperson',
  '기자': 'Journalist',
  '마케터': 'Marketer',
  '카피라이터': 'Copywriter',
  '기업가': 'Entrepreneur',
  '발명가': 'Inventor',
  '투자자': 'Investor',
  '경영자': 'Manager',
  '프로젝트 관리자': 'Project Manager',
  '재무 분석가': 'Financial Analyst',
  '교사': 'Teacher',
  '인사 담당자': 'HR Manager',
  '홍보 전문가': 'PR Expert',
  '정치인': 'Politician',
  '코치': 'Coach',
  '목사': 'Pastor',
  'CEO': 'CEO',
  '경영 컨설턴트': 'Management Consultant',
  '변호사': 'Lawyer',
  '마이스터고 지도': 'Meister High Map',
  '만든 사람들': 'Creators',
  'TOP 10 이외의 전체 기업': 'All Companies outside TOP 10',
  '개': ' companies',
  '전체': 'All',
  '트래픽 리포트': 'Traffic Report',
  '설정': 'Settings',
  '로그인': 'Login',
  '구글 로그인': 'Login with Google',
  '회원가입': 'Sign Up',
  '로그아웃': 'Logout',
  '홍보 페이지로 이동': 'Go to Promo Page',
  '게스트': 'Guest',
  '마이페이지': 'My Page',
  '홈': 'Home',
  '성장다이어리': 'Growth Diary',
  '자격증 가이드': 'Certificate Guide',
  '나만의 기업 찾기': 'Find My Company',
  'MBTI검사': 'MBTI Test',
  'MBTI 검사': 'MBTI Test',
  '홀랜드 진로적성 검사': 'Holland Career Test',
  '홀랜드 검사': 'Holland Test',
  '내 손으로 만들어가는': 'Building with my own hands',
  '당신만의 멋진 계단': 'Your Own Amazing Stairs',
  '당신의 노력의 땀방울이 꿈을 이루는': 'Every drop of your effort will become',
  '가장 단단한 다리가 되어줄 거에요.': 'the solid bridge to achieve your dreams.',
  '무료로 시작하기': 'Start for Free',
  '왜 MyStair가 필요할까요?': 'Why do you need MyStair?',
  '마이스터고 학생들의 교육 및 취업 준비 과정에서 발생하는 핵심 고민들입니다.': 'Core challenges faced by vocational students during career & job preparation.',
  '목표 달성의 막막함': 'Uncertainty in Goal Achievement',
  '경험의 빠른 휘발': 'Rapid Loss of Experiences',
  '맞춤 소재 연결의 어려움': 'Difficulty Connecting Tailored Experiences',
  '커리어 코칭 계단, MyStair': 'Career Coaching Staircase, MyStair',
  '매일 쌓인 실습 기록을 지원 기업 맞춤형 자소서 소재로 정밀 추출해 드립니다.': 'We precisely extract your daily practice records into tailored cover letter topics for target companies.',
  '나의 맞춤 기업 찾기': 'Find My Tailored Company',
  '경험 기록 & 노력 일수 시각화': 'Record Experience & Visualize Effort Days',
  '나의 전공학과, 성향(MBTI/홀랜드), 성장 기록을 바탕으로 나에게 가장 잘 어울리는 꿈의 기업을 AI가 매칭해 줍니다.': 'AI matches the best dream company for you based on your major, personality (MBTI/Holland), and growth records.',
  '교내외 실습, 대회 경험을 기록하세요. 매일 기록할 때마다 캘린더에 완수 스탬프가 적재되어 성취감을 높입니다.': 'Record internal/external lab practice and competition experiences. A completion stamp is placed on your calendar every day.',
  '맞춤 추천 기업 탐색': 'Explore Recommended Companies',
  '실습 일지 기록': 'Record Practice Journal',
  '연속 달성 스탬프': 'Streak Achievement Stamps',
  '실시간 AI 커리어 코칭 상담': 'Real-time AI Career Coaching',
  '어디서나 간편하고 신속하게 나만의 AI 진로 상담사와 대화하며 취업 방향성을 정립하세요.': 'Easily and quickly consult with your own AI career advisor anytime to establish your employment direction.',
  '실시간 Q&A': 'Real-time Q&A',
  '대기업/공기업 맞춤 자소서 원클릭 가공': 'One-click Cover Letter Processing for Large/Public Corps',
  '캘린더와 다이어리에 적어둔 경험들이 지원서 문항별 입체적인 STAR 자소서 문장으로 자동 변환됩니다.': 'Experiences in your calendar & diary are automatically converted into 3D STAR cover letter sentences for application prompts.',
  'NCS 기반 자동 매칭': 'NCS-based Auto Matching',
  'AI 문장 가공': 'AI Sentence Processing',
  '자격증 & 진로 로드맵': 'Certificates & Career Roadmap',
  '직무별 필수 국가기술자격증과 시험 일정, 우대 기업 정보를 한눈에 파악하세요.': 'Check required national technical certifications, exam schedules, and preferred companies by job at a glance.',
  '우대 자격증 조회': 'View Preferred Certificates',
  '자주 묻는 질문 (FAQ)': 'Frequently Asked Questions (FAQ)',
  '서비스에 대해 가장 자주 문의하시는 질문들을 모았습니다.': 'We gathered the most frequently asked questions about our service.',
  '빛나는 기술인으로 성장하는 여정, MyStair가 당신의 든든한 날개가 되어줄게요': 'A journey to grow into a shining skilled professional, MyStair will be your strong wings',
  '마이스터고 학생들을 위한 맞춤형 진로 로드맵': 'Customized career roadmap for vocational high school students',
  'AI 컨설턴트와 함께하는 스마트한 취업 준비': 'Smart job preparation with an AI consultant',
  '나의 잠재력을 발견하고 내일의 명장으로 거듭나는 첫걸음': 'The first step to discover your potential and become tomorrow master',
  '자격증부터 취업까지, 당신만의 특별한 커리어 스토리': 'From certification to employment, your own special career story',
  '현업 전문가의 인사이트와 맞춤형 진로 추천': 'Industry expert insights and customized career recommendations',
  '성장의 계단': 'Stairs of Growth',
  '나의 전공, 적성, 관심 분야에 맞는 기업을 검색하거나 추천받아보세요!': 'Search or get recommendations for companies matching your major, aptitude, and interest!',
  '나만의 기업찾기 (대기업/공기업 TOP 10)': 'Find My Company (Large/Public Corps TOP 10)',
  '대표 대기업 & 공기업 리스트': 'Top Large & Public Companies List',
  '성장기록 기반 우수 기업 매칭': 'Growth Record-Based Top Company Matching',
  '이전 대화 이어하기': 'Continue Previous Chat',
  '기본 프로필 정보': 'Basic Profile Info',
  '기본 정보': 'Basic Info',
  '학교': 'High School',
  '전공/학과': 'Major/Department',
  '목표 희망 기업': 'Target Companies',
  '나의 진로 적성 분석': 'My Career Aptitude Analysis',
  '완료': 'Done',
  '취소': 'Cancel',
  '희망 기업 추가': 'Add Target Company',
  '회사명을 입력하세요': 'Enter company name',
  '비밀번호를 입력하세요': 'Enter your password',
  '비밀번호': 'Password',
  '비밀번호 확인': 'Confirm Password',
  '새비밀번호입력': 'Enter new password',
  '가입하고 시작해보세요.': 'Sign up and get started.',
  '이메일을 입력하고 시작하세요.': 'Enter your email to get started.',
  '이메일': 'Email',
  '다음으로': 'Let\'s go',
  '처리 중...': 'Processing...',
  '계정이 없으신가요?': 'Don\'t have an account?',
  '이미 계정이 있으신가요?': 'Already have an account?',
  '돌아가기': 'Back',
  '유효한 이메일을 입력해주세요.': 'Please enter a valid email.',
  '비밀번호를 입력해주세요.': 'Please enter your password.',
  '이메일 또는 비밀번호가 올바르지 않습니다.': 'Invalid email or password.',
  '로그인 중 오류가 발생했습니다.': 'An error occurred during login.',
  '8글자 이상이여야 합니다': 'Must be at least 8 characters.',
  '비밀번호가 일치하지 않습니다': 'Passwords do not match.',
  '이미 가입된 이메일입니다.': 'This email is already registered.',
  '회원가입이 완료되었습니다. 로그인해주세요.': 'Registration complete. Please log in.',
  '나에게 꼭 맞는 기업 찾기': 'Find the Right Company for You',
  '전공과 진로 적성을 분석하여 AI가 추천하는 기업 리스트입니다': 'List of companies recommended by AI analyzing your major and career aptitude',
  '나의 매칭 추천 기업 (TOP 10)': 'My Top Matched Companies (TOP 10)',
  '대기업 TOP 10': 'Large Corps TOP 10',
  '공기업 TOP 10': 'Public Corps TOP 10',
  '나머지 기업 찾기': 'Find Other Companies',
  '전체 기업': 'All Companies',
  '기업명을 검색하세요': 'Search company name...',
  '기업 정보': 'Company Information',
  '기업 상세 정보': 'Company Details',
  '주요 사업 분야': 'Key Business Sector',
  '기업 규모': 'Company Size',
  '닫기': 'Close',
  '⚠️ \'Data/certificates.json\' 데이터를 불러올 수 없습니다.': '⚠️ Unable to load certification data.',
  '필기 응시료': 'Written Exam Fee',
  '마이스터고 추천 자격증 가이드': 'Recommended Certificates Guide',
  '전공 분야별 핵심 자격증 정보와 취득 로드맵을 확인하세요': 'Check core certification info and roadmap by major field',
  '전체 전공': 'All Majors',
  '자격증 상세 정보': 'Certificate Details',
  '시험 일정': 'Exam Schedule',
  '우대 기업': 'Preferred Companies',
  '마이스터고 학생을 위한 MBTI 성격유형 검사': 'MBTI Personality Test for Vocational High Students',
  'MBTI 성격 유형 검사': 'MBTI Personality Type Test',
  '32가지 MBTI': '32 MBTI',
  '32가지 MBTI 진로 적성 검사': '32 MBTI Career Aptitude Test',
  '32가지 MBTI\n진로 적성 검사': '32 MBTI Career Aptitude Test',
  '전국 마이스터고 맞춤형 MBTI 진로 적성 검사': 'Tailored MBTI Career Test for Vocational High Students',
  '나의 성격 유형(E/I, S/N, T/F, J/P)과 자아 지표(A/T)를 정밀 분석하여 나에게 꼭 맞는 맞춤형 직무를 추천해 드립니다.': 'Analyze your personality type (E/I, S/N, T/F, J/P) and self-indicator (A/T) to recommend tailored job roles.',
  '나의 성격 유형(E/I, S/N, T/F, J/P)과 자아 지표(A/T)를 정밀 분석하여\n나에게 꼭 맞는 맞춤형 직무를 추천해 드립니다.': 'Analyze your personality type (E/I, S/N, T/F, J/P) and self-indicator (A/T) to recommend tailored job roles.',
  '⏱ 소요시간 약 7분': '⏱ Approx. 7 mins',
  '소요시간 약 7분': 'Approx. 7 mins',
  '📝 총 60문항': '📝 60 Questions Total',
  '총 60문항': '60 Questions Total',
  '🎯 32가지 정밀 성격 분석': '🎯 32 Detailed Personality Analyses',
  '32가지 정밀 성격 분석': '32 Detailed Personality Analyses',
  '검사 시작하기': 'Start Test',
  '문항': 'Question',
  '1. 전혀 그렇지 않다': '1. Strongly Disagree',
  '2. 그렇지 않은 편이다': '2. Disagree',
  '3. 보통이다': '3. Neutral',
  '4. 그런 편이다': '4. Agree',
  '5. 매우 그렇다': '5. Strongly Agree',
  '전혀 그렇지 않다': 'Strongly Disagree',
  '그렇지 않은 편이다': 'Disagree',
  '보통이다': 'Neutral',
  '그런 편이다': 'Agree',
  '매우 그렇다': 'Strongly Agree',
  '← 이전 문항': '← Previous Question',
  '진로 적성 진단 결과': 'Career Aptitude Diagnosis Result',
  '선호도': 'Preference',
  '선호도 비율': 'Preference Ratio',
  '외향형 (E)': 'Extraversion (E)',
  '내향형 (I)': 'Introversion (I)',
  '직관형 (N)': 'Intuition (N)',
  '감각형 (S)': 'Sensing (S)',
  '사고형 (T)': 'Thinking (T)',
  '감정형 (F)': 'Feeling (F)',
  '판단형 (J)': 'Judging (J)',
  '인식형 (P)': 'Perceiving (P)',
  '자기확신형 (-A)': 'Assertive (-A)',
  '신중형 (-T)': 'Turbulent (-T)',
  '💡 성격 핵심 특성': '💡 Key Personality Traits',
  '🎯 추천 적성 직무 및 분야': '🎯 Recommended Aptitude Jobs & Fields',
  '👤 마이페이지로 이동하여 결과 확인하기': '👤 Go to My Page to Check Results',
  '📋 검사 결과 복사하기': '📋 Copy Test Results',
  '🔄 다시 검사하기': '🔄 Retest',
  '🏠 메인으로 돌아가기': '🏠 Return to Home',
  '검사 결과가 클립보드에 복사되었습니다!': 'Test results copied to clipboard!',
  '나의 성향과 어울리는 마이스터고 전공 및 직무를 알아봅니다.': 'Discover majors and jobs matching your personality.',
  'Holland\n직업적성검사': 'Holland Career Aptitude Test',
  'Holland 직업적성검사': 'Holland Career Aptitude Test',
  '전국 마이스터고 맞춤형 직업적성검사': 'Tailored Holland Career Test for Vocational High Students',
  '나의 흥미와 적성 유형(RIASEC)을 분석하여\n나에게 꼭 맞는 직업군과 직무를 추천해 드립니다.': 'Analyze your interest & aptitude type (RIASEC) to recommend tailored job fields.',
  '나의 흥미와 적성 유형(RIASEC)을 분석하여 나에게 꼭 맞는 직업군과 직무를 추천해 드립니다.': 'Analyze your interest & aptitude type (RIASEC) to recommend tailored job fields.',
  '🎯 6가지 흥미 유형 진단': '🎯 6 Interest Types Diagnosis',
  '6가지 흥미 유형 진단': '6 Interest Types Diagnosis',
  'Holland 진로 진단 결과': 'Holland Career Diagnosis Result',
  '적합도': 'Suitability',
  '💡 1순위: ': '💡 1st Priority: ',
  '💡 2순위: ': '💡 2nd Priority: ',
  '🎯 추천 맞춤 직무': '🎯 Recommended Custom Jobs',
  '홀랜드 진로 적성 검사': 'Holland Career Aptitude Test',
  '나의 진로 적성 코드 (RIASEC) 분석': 'Analyze My Career Aptitude Code (RIASEC)',
  '성장 다이어리': 'Growth Diary',
  '시험 일정 설정': 'Exam Schedule Settings',
  '달력 보기': 'Calendar View',
  '자소서 요약': 'Resume Summary',
  '1·2학기 중간 / 기말고사 시험 일정 설정': '1st & 2nd Semester Midterm/Final Exam Schedule Settings',
  '시험 기간을 설정하시면 성장 다이어리 달력에 📝 시험 그림 아이콘이 자동으로 표시됩니다.': 'When you set exam dates, 📝 exam icons will automatically appear on your Growth Diary calendar.',
  '📝 1학기 중간고사': '📝 1st Semester Midterm Exam',
  '💯 1학기 기말고사': '💯 1st Semester Final Exam',
  '📝 2학기 중간고사': '📝 2nd Semester Midterm Exam',
  '🎓 2학기 기말고사': '🎓 2nd Semester Final Exam',
  '1학기 중간고사': '1st Semester Midterm Exam',
  '1학기 기말고사': '1st Semester Final Exam',
  '2학기 중간고사': '2nd Semester Midterm Exam',
  '2학기 기말고사': '2nd Semester Final Exam',
  '일정 모두 비우기': 'Clear All Schedules',
  '샘플 일정 채우기': 'Fill Sample Schedule',
  '시험 일정 저장': 'Save Exam Schedule',
  '일기 쓰기': 'Write Diary',
  '+ 일기 쓰기': '+ Write Diary',
  '이전 달': 'Previous Month',
  '다음 달': 'Next Month',
  '성장 다이어리 작성': 'Create Growth Diary Entry',
  '성장 다이어리 수정': 'Edit Growth Diary Entry',
  '날짜 선택': 'Select Date',
  '오늘의 기분 / 태그': 'Today\'s Mood / Tags',
  '열정적': 'Passionate',
  '성취감': 'Accomplished',
  '깨달음': 'Enlightened',
  '성장중': 'Growing',
  '평온함': 'Peaceful',
  '제목': 'Title',
  '다이어리 제목을 입력하세요...': 'Enter diary title...',
  '태그 (엔터로 추가)': 'Tags (press enter to add)',
  '내용': 'Content',
  '오늘의 실습, 공부, 성취 경험이나 느낀 점을 자유롭게 적어보세요...': 'Feel free to write today\'s lab practice, study, achievements, or reflections...',
  '저장하기': 'Save',
  'AI 자소서 경험 요약 (STAR 공법 분석)': 'AI Resume Experience Summary (STAR Analysis)',
  '다이어리 기록을 분석하여 자소서 소재를 추출하고 있습니다...': 'Analyzing diary records to extract resume materials...',
  '각 경험을 탭과 타임라인 날짜별 STAR 공법으로 완벽히 분류 중입니다.': 'Classifying each experience with STAR method by tabs and dates.',
  '자격증 노력': 'Certification Efforts',
  '대내외 활동': 'Activities',
  '수상 및 성과': 'Awards & Achievements',
  '기타 성장경험': 'Other Growth Experiences',
  'Situation (상황 배경)': 'Situation (Background Context)',
  'Task (목표와 과제)': 'Task (Goals & Challenges)',
  'Action (내가 취한 구체적 행동)': 'Action (Specific Actions Taken)',
  'Result (최종 성과 및 내적 성장)': 'Result (Outcomes & Internal Growth)',
  '추출된 경험이 아직 없습니다': 'No extracted experiences yet',
  '해당 카테고리(자격증, 대내외활동 등) 관련 키워드가 다이어리나 프로필에 충분하지 않은 것 같아요. 일기에 관련 내용(시험, 실습, 성과, 대회 등)을 더 자세히 기록하면 AI가 정확히 분류해서 보여줍니다!': 'It seems keywords related to this category are insufficient in your diary or profile. Write more detailed entries to get automatic AI extraction!',
  '마이스터고 성장 다이어리': 'Vocational Growth Diary',
  '나의 하루 실습, 공부, 성장의 흔적을 기록하고 되돌아보세요': 'Record and reflect on your daily practice, study, and growth',
  '새 다이어리 작성': 'Write New Diary Entry',
  '제목을 입력하세요': 'Enter title',
  '오늘의 실습 내용과 깨달은 점을 작성해 보세요': 'Write about today\'s practice and insights',
  '작성 완료': 'Complete Entry',
  '오늘의 완수 스탬프': 'Today\'s Completion Stamp',
  '기록이 없습니다. 첫 번째 다이어리를 작성해 보세요!': 'No records found. Write your first diary entry!',
  '전국 마이스터고 및 특성화고 학생들의 더 높은 꿈과 내일을 응원하며': 'Cheering for the higher dreams and tomorrow of vocational high school students nationwide,',
  '더 직관적이고 완성도 높은 취업·진로 솔루션을 만들기 위해 기획하고 개발한 팀입니다.': 'a team that planned and developed an intuitive and complete employment & career solution.',
  '전국 마이스터고 및 특성화고 학생들의 더 높은 꿈과 내일을 응원하며 더 직관적이고 완성도 높은 취업·진로 솔루션을 만들기 위해 기획하고 개발한 팀입니다.': 'A team dedicated to creating an intuitive and complete career & employment platform for vocational students nationwide.',
  '마이스터고 커리큘럼 및 진로 데이터 분석, AI 프롬프트 엔지니어링 및 전체 웹 플랫폼 총괄 개발.': 'Curriculum & career data analysis, AI prompt engineering, and full platform development.',
  '학생들이 부담 없이 쉽게 마이페이지, 성장 일기, MBTI 및 홀랜드 검사를 이용할 수 있는 다크 글래스모피즘 인터페이스 설계.': 'Designed dark glassmorphism interface for easy access to My Page, Growth Diary, MBTI & Holland tests.',
  '전국 마이스터고 위치 데이터, 전공별 필수 자격증 추천 정보, 주요 대기업/공기업 가이드라인 수집 및 검증.': 'Location data of vocational schools, recommended certifications, and major company guidelines research.',
  
  // General texts in certificates
  '제한 없음 (연령, 학력, 경력 무관)': 'No restrictions (Regardless of age, education, or experience)',
  '제한 없음': 'No restrictions',
  '제한없음': 'No restrictions',
  '해당 없음': 'Not Applicable',
  '발전 5사': '5 Power Generation Companies',
  '발전5사': '5 Power Generation Companies',
  '모든 공기업': 'All Public Enterprises',
  '부품 제조업체': 'Component Manufacturing Companies',
  '기계 부품 제조사': 'Mechanical Component Manufacturers',
  '전국 제조업 생산/물류 현장': 'Manufacturing Production & Logistics Sites Nationwide',
  '수입차 공식 서비스센터': 'Imported Car Official Service Centers',
  'IT 서비스 기업': 'IT Service Companies',
  '대형 빌딩 관리업체': 'Large Building Management Companies',
  '에너지 공기업': 'Energy Public Enterprises',
  '대형병원/시설': 'Large Hospitals and Facilities',
  '반도체 장비사': 'Semiconductor Equipment Manufacturers',

  // Top Certificates & Descriptions
  '전기기능사': 'Electrician Craftsman',
  '전기 설비의 시공, 정비, 운용 및 관련 기기의 유지보수 작업을 수행하는 마이스터고 전기 계열 핵심 필수 자격증입니다.': 'An essential certification for Meister high school electrical departments, covering construction, maintenance, and operation of electrical installations and maintenance of related equipment.',
  
  '전산응용기계제도기능사': 'Craftsman Computer Aided Mechanical Drawing',
  'CAD 시스템을 활용해 기계 도면을 규격에 맞게 작성, 검토, 수정하는 정밀 기계 설계 대표 자격증입니다.': 'The representative certification for precision mechanical design, covering the drawing, review, and modification of mechanical blueprints using CAD systems.',
  
  '컴퓨터응용밀링기능사': 'Craftsman Computer Aided Milling',
  'CNC 밀링 머신 절삭 프로그램을 작성하고 부품을 정밀 가공하는 대표적인 금속 가공 자격입니다.': 'A representative metal processing qualification, covering the writing of CNC milling machine cutting programs and precision part machining.',
  
  '컴퓨터응용선반기능사': 'Craftsman Computer Aided Lathing',
  'CNC 선반 머신을 제어하여 회전체 부품을 정밀 가공 및 측정하는 정밀 공작 자격입니다.': 'A precision metalworking qualification, covering the control of CNC lathes to machine and measure precision rotating parts.',
  
  '설비보전기능사': 'Craftsman Maintenance',
  '플랜트 및 생산 자동화 설비의 기계·전기적 고장을 예방하고 보수 정비하는 스마트 팩토리 필수 자격입니다.': 'An essential smart factory qualification, covering preventive maintenance and repair of mechanical and electrical faults in plant and production automation facilities.',
  
  '위험물기능사': 'Craftsman Hazardous Materials',
  '인화성, 발화성 위험 물질의 안전 관리 및 관련 제조 시설 점검을 담당하는 화공계열 대표 법정 자격입니다.': 'A representative statutory qualification for chemical engineering, covering safety management of flammable and ignitable hazardous substances and inspection of related manufacturing facilities.',
  
  '화학분석기능사': 'Craftsman Chemical Analysis',
  '화학 물질의 정성·정량 분석 및 품질 관리를 위한 화학 실험 및 기기 분석을 수행하는 자격입니다.': 'A qualification for performing chemical experiments and instrumental analysis for qualitative/quantitative analysis and quality control of chemical substances.',
  
  '정보처리기능사': 'Craftsman Information Processing',
  '소프트웨어 프로그래밍 언어(C, Java, Python), 데이터베이스 및 알고리즘 기초를 평가하는 IT 자격입니다.': 'An IT qualification evaluating basic programming languages (C, Java, Python), databases, and core algorithms.',
  
  '자동차정비기능사': 'Craftsman Motor Vehicle Maintenance',
  '자동차 엔진, 기관, 샤시, 전기장치 구조를 점검, 진단하고 정비하는 모빌리티 분야 필수 자격입니다.': 'An essential qualification in mobility, covering inspection, diagnosis, and repair of car engines, chassis, and electrical devices.',
  
  '지게차운전기능사': 'Craftsman Forklift Truck Driving',
  '제조 및 물류 현장에서 지게차을 안전하게 조종해 화물을 적재, 하역, 수송하는 대표 취업 우대 자격입니다.': 'A key qualification for employment, covering safe operation of forklifts to load, unload, and transport cargo in manufacturing and logistics sites.',
  
  '공조냉동기계기능사': 'Craftsman Air-Conditioning & Refrigerating Machinery',
  '냉동 장치 및 공기조화 설비를 설치, 운전, 정비하는 시설관리 및 설비 분야 필수 자격입니다.': 'An essential qualification for facility and equipment management, covering installation, operation, and maintenance of refrigeration and air conditioning systems.',
  
  '에너지관리기능사': 'Craftsman Energy Management',
  '보일러 및 열사용 기기의 에너지 효율 운전과 안전 관리를 담당하는 자격입니다.': 'A qualification covering energy-efficient operation and safety management of boilers and thermal equipment.',
  
  '승강기기능사': 'Craftsman Elevator',
  '엘리베이터, 에스컬레이터 등 승강 설비를 시공 및 안전 보수하는 자격입니다.': 'A qualification for constructing and safely maintaining elevators, escalators, and other lift equipment.',
  
  '피복아크용접기능사': 'Craftsman Shielded Metal Arc Welding',
  '아크 용접봉을 이용해 철골 구조물 및 관재를 정밀 용접하는 전통 기술자격입니다.': 'A traditional technical qualification for precise welding of steel structures and pipes using arc welding rods.',
  
  '전자기능사': 'Craftsman Electronics',
  '전자 회로의 설계, 부품 조립, 수리 및 측정 테스트 작업을 안전하게 수행하는 자격입니다.': 'A qualification covering safe design, component assembly, repair, and measurement/testing of electronic circuits.',
  
  '한국사능력검정시험 (심화)': 'Korean History Proficiency Test (Advanced)',
  '한국사에 대한 체계적 이해와 역사적 사고력을 평가하는 시험으로 공기업 필수 가산점 자격증입니다.': 'An exam evaluating systematic understanding of Korean history and historical thinking, which is an essential qualification for extra points in public enterprises.',
  
  '컴퓨터활용능력 1급': 'Computer Literacy Level 1',
  '스프레드시트(Excel) 및 데이터베이스(Access) 실무 활용 능력을 평가하는 대표 사무 자동화 자격입니다.': 'A representative office automation qualification evaluating practical spreadsheet (Excel) and database (Access) skills.',
  '컴퓨터활용능력 2급': 'Computer Literacy Level 2',
  'SQLD (SQL 개발자)': 'SQL Developer (SQLD)',
  '전기공사산업기사 (과정평가형)': 'Industrial Engineer Electrical Construction (Course-Evaluation)',
  '기계설계산업기사 (과정평가형)': 'Industrial Engineer Mechanical Design (Course-Evaluation)',
  '바이오화학제품제조기능사': 'Craftsman Biochemical Product Manufacturing',
  '항공기체정비기능사': 'Craftsman Aircraft Airframe Maintenance',
  '굴착기운전기능사': 'Craftsman Excavator Driving',
  '초경량비행장치 조종자 (드론 1종)': 'Ultra-light Flying Device Pilot (Drone Class 1)',
  '가스기능사': 'Craftsman Gas',
  '가스티그용접기능사': 'Craftsman Gas Tungsten Arc Welding',
  '공유압기능사': 'Craftsman Pneumatic and Hydraulic',
  '기계정비기능사': 'Craftsman Mechanical Maintenance',
  '전자캐드기능사': 'Craftsman Electronic CAD',
  '신재생에너지발전설비기능사(태양광)': 'Craftsman Renewable Energy Power Generation Equipment (Solar)',
  '3D프린터운용기능사': 'Craftsman 3D Printer Operation',
  '웹디자인기능사': 'Craftsman Web Design',
  '컴퓨터그래픽스운용기능사': 'Craftsman Computer Graphics',
  '환경기능사': 'Craftsman Environmental',
  '측량기능사': 'Craftsman Surveying',
  '지적기능사': 'Craftsman Cadastral',
  '무선설비기능사': 'Craftsman Wireless Communication Equipment',
  '정보통신기능사': 'Craftsman Information Telecommunication',
  '네트워크관리사 2급': 'Network Administrator Class 2',
  '항공기관정비기능사': 'Craftsman Aircraft Engine Maintenance',
  '자동차보수도장기능사': 'Craftsman Motor Vehicle Painting',
  '자동차차체수리기능사': 'Craftsman Motor Vehicle Body Repair',
  '이산화탄소가스아크용접기능사': 'Craftsman Carbon Dioxide Gas Arc Welding',
  '로더운전기능사': 'Craftsman Loader Driving',
  '롤러운전기능사': 'Craftsman Roller Driving',
  '천장크레인운전기능사': 'Craftsman Overhead Crane Driving',
  '컨테이너크레인운전기능사': 'Craftsman Container Crane Driving',
  '정밀측정기능사': 'Craftsman Precision Measurement',
  '전자계산기기능사': 'Craftsman Computer',
  '생산자동화기능사': 'Craftsman Production Automation',
  '배전전공': 'Distribution Lineman',
  '소방안전관리자 2급': 'Fire Safety Manager Class 2',
  '소방안전관리자 1급': 'Fire Safety Manager Class 1',
  'ADsP (데이터분석 준전문가)': 'ADsP (Advanced Data Analytics Semi-Professional)',
  '리눅스마스터 2급': 'Linux Master Class 2',
  'ITQ 한글': 'ITQ Hangul (Korean Word Processing)',
  'ITQ 엑셀': 'ITQ Excel',
  'ITQ 파워포인트': 'ITQ PowerPoint',
  'ITQ OA Master': 'ITQ OA Master',
  'MOS Master': 'MOS Master',
  '워드프로세서': 'Word Processor',
  '전산회계 1급': 'Computerized Accounting Class 1',
  '전산회계 2급': 'Computerized Accounting Class 2',
  '전산세무 2급': 'Computerized Tax Accounting Class 2',
  '전산회계운용사 2급': 'Computerized Accounting Administrator Class 2',
  '전산회계운용사 3급': 'Computerized Accounting Administrator Class 3',
  '매경TEST (우수/최우수)': 'MaeKyung TEST (Outstanding/Outstanding+)',
  'TESAT (S급/1급/2급)': 'TESAT (Grade S/1/2)',
  '물류관리사': 'Logistics Manager',
  '유통관리사 2급': 'Distribution Manager Class 2',
  '무역영어 1급': 'Trade English Class 1',
  'KBS한국어능력시험': 'KBS Korean Language Proficiency Test',
  'ToKL (국어능력인증시험)': 'ToKL (Test of Korean Language)',
  'TOEIC': 'TOEIC',
  'TOEIC Speaking': 'TOEIC Speaking',
  'OPIc': 'OPIc',
  'JPT': 'JPT (Japanese Proficiency Test)',
  'HSK 4급': 'HSK Level 4',
  '전기공사산업기사': 'Industrial Engineer Electrical Construction',
  '전기산업기사': 'Industrial Engineer Electrical',
  '한국철도공사': 'Korea Railroad Corporation (KORAIL)',
  '기계설계산업기사': 'Industrial Engineer Mechanical Design',
  '위험물산업기사': 'Industrial Engineer Hazardous Materials',
  '정보처리산업기사': 'Industrial Engineer Information Processing',
  'SQLD': 'SQL Developer (SQLD)',
  '기아': 'Kia',
  'CJ대한통운': 'CJ Logistics',
  '삼성전자 물류센터': 'Samsung Electronics Logistics Center',
  '삼성물산': 'Samsung C&T',
  'LG전자': 'LG Electronics',
  '지역난방공사': 'Korea District Heating Corporation',
  '현대엘리베이터': 'Hyundai Elevator',
  '오티스엘리베이터': 'Otis Elevator',
  '쉰들러': 'Schindler',
  'HD현대중공업': 'HD Hyundai Heavy Industries',
  '한화오션': 'Hanwha Ocean',
  '삼성중공업': 'Samsung Heavy Industries',
  'LG이노텍': 'LG Innotek',
  '전국 모든 공기업': 'All Public Enterprises Nationwide',
  '네이버': 'Naver',
  '카카오': 'Kakao',
  '금융권(은행/카드사)': 'Financial Sector (Banks/Cards)',
  'IT 부서': 'IT Department',
  'LH공사': 'Korea Land and Housing Corporation (LH)',
  '마이페이지로 이동하기': 'Go to My Page',
  '예: 전기기능사 회로 실습 성공 기록': 'e.g., Electrical Craftsman circuit practice success record',
  '오늘 배운 실무 기술, 시험 공부 분량, 느낀 점을 자유롭게 기록해보세요...': 'Feel free to record what practical skills you learned today, exam study progress, and your reflections...',
  '날짜': 'Date',
  '오늘의 기분': "Today's Mood",
  '오늘의 성장 기록 및 일기 내용': "Today's Growth Record & Diary Content",
  '일기 삭제': 'Delete Diary',
  '수정 완료': 'Edit Completed',
  '일기 저장': 'Save Diary',
  '다이어리 기록이 삭제되었습니다.': 'The diary record has been deleted.',
  '성장 다이어리가 성공적으로 저장되었습니다!': 'Growth diary saved successfully!',
  '시험 일정이 성공적으로 저장되었습니다!': 'Exam schedule saved successfully!',
  '모든 일정을 비웠습니다.': 'Cleared all schedules.',
  '샘플 시험 일정이 적용되었습니다.': 'Sample exam schedule applied.',
  '이 다이어리 기록을 삭제하시겠습니까?': 'Are you sure you want to delete this diary record?',
  '제목과 내용을 입력해주세요.': 'Please enter a title and content.',
  '서버에서 요약을 생성하지 못했습니다.': 'Failed to generate summary from the server.',
  '요약 중 오류가 발생했습니다.': 'An error occurred during summarization.',
  '구조화 탭 로딩 실패': 'Structured Tab Loading Failed',
  'AI 요약 데이터가 JSON 규격에 맞지 않아 일반 텍스트 형태로 출력합니다. 아래 분석글을 참고해 주세요.': 'The AI summary data is not in JSON format, so it is displayed in plain text. Please refer to the analysis below.',
  '내가 취한 구체적 행동': 'Specific actions I took',
  '최종 성과 및 내적 성장': 'Final achievements and inner growth',
  '날짜 미지정': 'No Date Specified',
};

const koToZhMap: Record<string, string> = {
  '분석': '分析',
  '전문성': '专业性',
  '독립': '独立',
  '집중': '专注',
  '연구': '研究',
  '소통': '沟通',
  '협력': '合作',
  '팀워크': '团队合作',
  '리더십': '领导力',
  '글로벌': '全球',
  '현실': '现实',
  '현장': '现场',
  '품질': '质量',
  '실용': '实用',
  '안전': '安全',
  '원칙': '原则',
  '혁신': '创新',
  '창의': '创意',
  '비전': '愿景',
  '도전': '挑战',
  '미래': '未来',
  '논리': '逻辑',
  '기술': '技术',
  '효율': '效率',
  '합리': '合理',
  '인간미': '人情味',
  '고객': '客户',
  '공감': '共鸣',
  '계획': '计划',
  '체계': '体系',
  '철저': '彻底',
  '책임': '责任',
  '유연': '灵活',
  '변화': '变化',
  '자율': '自主',
  '적응': '适应',
  '기계': '机械',
  '설비': '设备',
  '제조': '制造',
  '생산': '生产',
  '설계': '设计',
  '개발': '开发',
  '디자인': '设计',
  '독창': '独创',
  '아이디어': '创意',
  '서비스': '服务',
  '지원': '支持',
  '성장': '成长',
  '열정': '热情',
  '경쟁력': '竞争力',
  '관리': '管理',
  '대기업': '大企业',
  '공공기관': '公共机构',
  '공기업': '国企',
  '공공': '公共',
  '공사': '公社',
  '공단': '公团',
  '성장 다이어리': '成长日记',
  '자격증 가이드': '证书指南',
  '나만의 기업찾기': '寻找专属企业',
  'MBTI검사': 'MBTI测评',
  '홀랜드 진로적성 검사': '霍兰德职业兴趣测评',
  '마이페이지': '个人主页',
  '로그아웃': '登出',
  '홍보 페이지로 이동': '前往宣传页面',
  '구글 로그인': '谷歌登录',
  '프로필': '个人资料',
  '한국어': '韩语',
  '영어': '英语',
  '중국어': '中文',
  '만든 사람들': '主创团队',
  '트래픽 리포트': '流量报告',
  '설정': '设置',
  '로그인': '登录',
  '환영합니다': '欢迎',
  '이전 질문 기록 보기': '查看历史提问记录',
  '이전 기록': '历史记录',
  '새로운 대화 시작하기': '开始新对话',
  '새 대화 시작': '开始新对话',
  'MyStair AI가 프로필과 다이어리를 바탕으로 나만의 기업을 탐색 중입니다...': 'MyStair AI 正在根据您的个人资料和日记探索匹配的企业...',
  '추천 질의 예시': '推荐问题示例',
  '마이스터고 졸업 후 대기업 취업 전략 및 필수 자격증은?': '迈斯特高中毕业后进入大企业的求职策略和必备证书是什么？',
  '내 성장 다이어리를 분석해서 자소서 경험 뽑아줘': '分析我的成长日记并提取自荐信素材',
  '내 전공과 MBTI에 맞는 추천 직무와 기업 알려줘': '告诉我符合我的专业和 MBTI 的推荐岗位与企业',
  '성장의 계단': '成长的阶梯',
  '나의 전공, 적성, 관심 분야에 맞는 기업을 검색하거나 추천받아보세요!': '搜索或获取符合您的专业、性格和兴趣领域的企业推荐！',
  '나만의 기업찾기 (대기업/공기업 TOP 10)': '寻找专属企业 (大企业/国企 TOP 10)',
  '대표 대기업 & 공기업 리스트': '代表性大企业 & 国企名单',
  '성장기록 기반 우수 기업 매칭': '基于成长记录的优秀企业匹配',
  '이전 대화 이어하기': '继续之前的对话',
  '자격증 NAVI': '证书导航',
  '우리가 원하는 자격증을 한눈에!': '我们想要的证书一目了然！',
  '마이스터고 자격증 정밀 검색': '迈斯特高中证书精细搜索',
  '자격증명, 전공 분야, 가산점 적용 기업(삼성, 한전, 코레일 등)을 입력해보세요.': '请输入证书名称、专业领域或加分企业（如三星、韩国电力、Korail等）。',
  '자격증명, 우대기업, 카테고리 검색...': '搜索证书名称、意向企业或类别...',
  '전체보기': '查看全部',
  '자격증 데이터를 불러오는 중입니다...': '正在加载证书数据...',
  '🔍 검색 조건과 일치하는 자격증이 없습니다.': '🔍 没有符合搜索条件的证书。',
  '평균 합격률': '平均合格率',
  '실기 응시료': '实操考试费',
  '자세히 보기 & 접수하기 ➔': '查看详情 & 报名 ➔',
  '📝 자격증 개요': '📝 证书概述',
  '📋 응시 자격 조건': '📋 报考资格条件',
  '⭐ 난이도': '⭐ 难度',
  '📊 평균 합격률': '📊 平均合格率',
  '💰 필기 응시료': '💰 笔试考试费',
  '🛠️ 실기 응시료': '🛠️ 实操考试费',
  '🏢 우대 및 가산점 반영 기업': '🏢 享有优待或加分的企业',
  '🔗 연계 / 관련 자격증': '🔗 衔接 / 相关证书',
  '👉 공식 접수 사이트 바로가기': '👉 前往官方报名网站',
  '서버에서 요약을 생성하지 못했습니다.': '服务器未能生成摘要。',
  '요약 중 오류가 발생했습니다.': '摘要过程中发生错误。',
  '정보처리기능사 실기 공부 3일차': '信息处理技能士实操学习第3天',
  '오늘 알고리즘 문제 5개를 풀었다. 정렬 알고리즘 개념이 이제서야 완전히 이해되었다! 내일은 데이터베이스 SQL 기출문제를 집중 정리해야겠다.': '今天解决了5道算法题。终于完全理解了排序算法的概念！明天我要集中整理数据库SQL真题。',
  '시험 일정이 성공적으로 저장되었습니다!': '考试日程已成功保存！',
  '제목과 내용을 입력해주세요.': '请输入标题和内容。',
  '성장 다이어리가 성공적으로 저장되었습니다!': '成长日记保存成功！',
  '저장 중 오류가 발생했습니다.': '保存过程中发生错误。',
  '이 다이어리 기록을 삭제하시겠습니까?': '您确定要删除这篇日记记录吗？',
  '다이어리 기록이 삭제되었습니다.': '日记记录已删除。',
  '삭제 중 오류가 발생했습니다.': '删除过程中发生错误。',
  '시험 일정 설정': '设置考试日程',
  '달력 보기': '查看日历',
  '자소서 요약': '自荐信摘要',
  '1·2학기 중간 / 기말고사 시험 일정 설정': '设置第1、2学期期中 / 期末考试日程',
  '시험 기간을 설정하시면 성장 다이어리 달력에 📝 시험 그림 아이콘이 자동으로 표시됩니다.': '设置考试期间后，成长日记日历上会自动显示 📝 考试图标。',
  '1학기 중간고사': '第1学期期中考试',
  '1학기 기말고사': '第1学期期末考试',
  '2학기 중간고사': '第2学期期中考试',
  '2학기 기말고사': '第2学期期末考试',
  '모든 일정을 비웠습니다.': '已清空所有日程。',
  '일정 모두 비우기': '清空所有日程',
  '샘플 시험 일정이 적용되었습니다.': '已应用示例考试日程。',
  '샘플 일정 채우기': '填充示例日程',
  '시험 일정 저장': '保存考试日程',
  '현재 선택된 희망 기업': '当前选择的意向企业',
  '현재 선택된 희망 기업 ': '当前选择的意向企业 ',
  '저장 완료': '保存完毕',
  '전체 편집 모드입니다. 정보를 수정한 후 [전체 저장] 버튼을 눌러주세요.': '处于全编辑模式。修改信息后请点击 [保存全部] 按钮。',
  '나의 성장의 계단 & 진로 프로필': '我的成长阶梯 & 职业生涯个人资料',
  '나의 성장의 계단 & 진로 프로필 ': '我的成长阶梯 & 职业生涯个人资料 ',
  '성장 다이어리 ': '成长日记 ',
  '자소서 요약 생성': '生成自荐信摘要',
  '전체 저장': '保存全部',
  '전체 편집 모드': '全编辑模式',
  '보이기': '显示',
  '숨기기': '隐藏',
  '희망 기업': '意向企业',
  '진로 성향 검사 기록 (MBTI & Holland)': '职业兴趣倾向测评记录 (MBTI & 霍兰德)',
  '검사하러 가기': '前往测评',
  '나의 성장 기록 리포트': '我的成长记录报告',
  'AI의 자소서 핵심 역량 분석': 'AI 自荐信核心能力分析',
  '기록된 다이어리를 바탕으로 자소서 작성에 필요한 4가지 핵심 가치 역량을 자동으로 분석합니다. (매주 업데이트)': '根据记录的日记，自动分析撰写自荐信所需的4个核心价值能力。（每周更新）',
  '부족한 경험 보완 가이드': '补充缺失经验指南',
  '목표 기업 합격을 위해 남은 학기 동안 어떤 경험을 추가로 쌓으면 좋을지 맞춤 가이드를 제공합니다.': '为您提供定制指南，指导您在剩余的学期里应当补充哪些经验以顺利通过目标企业。',
  '나만의 자소서 소재 요약': '专属自荐信素材摘要',
  '성장기록 중 자소서에 바로 활용할 수 있는 STAR 기법 기반의 핵심 경험 요약입니다.': '从成长记录中提取的可直接用于自荐信的基于 STAR 原则的核心经验摘要。',
  '💡 자소서 작성 Tip': '💡 自荐信撰写技巧',
  '이 경험은 자기소개서의 \'어려움을 극복한 사례\' 또는 \'협업을 통한 문제 해결\' 문항에 배치하기 가장 좋습니다.': '这段经历最适合放在自荐信的“克服困难的案例”或“通过协作解决问题”的问题中。',
  '상황(Situation)': '情境(Situation)',
  '과제(Task)': '任务(Task)',
  '행동(Action)': '行动(Action)',
  '결과(Result)': '结果(Result)',
  '자소서 핵심 역량 요약 생성 중...': '正在生成自荐信核心能力摘要...',
  '다이어리 성장 일기': '成长日记列表',
  '성장 일기': '成长日记',
  '일기 쓰기': '写日记',
  '다이어리가 비어 있습니다.': '日记为空。',
  '오늘의 학습, 실습, 시험 공부 내용을 첫 일기로 남겨보세요!': '留下您的第一篇关于今天学习、实操或备考内容的日记吧！',
  '성장 다이어리 분석': '成长日记分析',
  '작성한 일기들을 종합하여 내 강점 키워드를 도출합니다.': '综合已撰写的日记，提炼出我的优势关键词。',
  '공부 시간': '学习时间',
  '실습 시간': '实操时间',
  '성장 다이어리를 3개 이상 작성하시면, AI 기반 종합 분석과 맞춤 자소서 가이드가 활성화됩니다!': '撰写3篇以上成长日记后，基于 AI 的综合分析和定制自荐信指南就会激活！',
  '🌐 홍보사이트 보기': '🌐 查看宣传页面',
  '기록 완료': '记录完毕',
  '수정 완료': '编辑完成',
  '일기 저장': '保存日记',
  '일기 삭제': '删除日记',
  '날짜': '日期',
  '오늘의 기분': '今日心情',
  '오늘의 성장 기록 및 일기 내용': '今日成长记录及日记内容',
  '예: 전기기능사 회로 실습 성공 기록': '例如：电气技能士电路实操成功记录',
  '오늘 배운 실무 기술, 시험 공부 분량, 느낀 점을 자유롭게 기록해보세요...': '自由记录今天学到的实操技术、考试学习进度、感想等...',
  '마이페이지로 이동하기': '前往个人主页',
  'LH공사': '韩国土地住宅公社',
  '금융권(은행/카드사)': '金融界(银行/信用卡公司)',
  'IT 부서': 'IT 部门',
  '카카오': 'Kakao',
  '네이버': 'Naver',
  '라인': 'Line',
  '쿠팡': 'Coupang',
  '우아한형제들': 'Woowa Brothers',
  '당근': 'Daangn',
  '토스': 'Toss',
  '중소/중견기업': '中小/中型企业',
  '창업/스타트업': '创业/初创公司',
  '기타': '其他',
  '마이스터고': '迈斯特高中',
  '학교': '学校',
  '학과': '专业/科系',
  '성격 유형 (MBTI)': '性格类型 (MBTI)',
  '직업 흥미 (Holland)': '职业兴趣 (霍兰德)',
  '희망 취업 기업': '意向就业企业',
  '희망 기업 추가': '添加意向企业',
  '희망 기업명을 검색해 추가할 수 있습니다.': '可以搜索并添加意向企业名称。',
  '추천 기업목록': '推荐企业名单',
  '나머지 추천 기업': '其余推荐企业',
  '목록에서 선택하여 희망 기업에 추가해 보세요.': '从列表中选择并添加到意向企业中。',
  '추가': '添加',
  '선택됨': '已选择',
  '마이스터고 학생들의 자소서 작성, 목표 기업매칭, 취업 준비를 돕는 AI 멘토 서비스': '辅助迈斯特高中学生撰写自荐信、匹配目标企业和准备就业的 AI 导师服务',
  '새로운 질문을 입력해보세요...': '输入新问题...',
  '질문하는 중...': '提问中...',
  '답변을 완료했습니다.': '解答完毕。',
  '무료로 시작하기': '免费开始使用',
  '지금 시작하기': '现在开始',
  '서비스 기획 및 스토리보드 설계, 브랜드 소개를 위한 홍보페이지 UI/UX 디자인 및 인터랙션 담당.': '负责服务策划、原型设计，以及用于 brand 介绍的宣传页面 UI/UX 设计与交互。',
  '홍보 전문가': '宣传专家',
  '검사 시작하기': '开始测试',
  '결과 확인하기': '查看结果'
};

const translations = {
  ko: {
    'nav.map': '마이스터고 지도',
    'nav.creators': '만든 사람들',
    'nav.traffic': '트래픽 리포트',
    'nav.settings': '설정',
    'nav.login': '로그인',
    'dashboard.welcome': '환영합니다',
    'login.title.signup': '회원가입',
    'login.title.login': '환영합니다',
    'login.subtitle.signup': '가입하고 시작해보세요.',
    'login.subtitle.login': '이메일을 입력하고 시작하세요.',
    'login.email': '이메일',
    'login.password': '비밀번호',
    'login.password.confirm': '비밀번호 확인',
    'login.password.enter': '비밀번호를 입력하세요',
    'login.button.signup': '회원가입',
    'login.button.login': '로그인',
    'login.button.processing': '처리 중...',
    'login.button.letsgo': '다음으로',
    'login.no_account': '계정이 없으신가요?',
    'login.has_account': '이미 계정이 있으신가요?',
    'login.back': '돌아가기',
    'login.placeholder.email': 'you@example.com',
    'login.placeholder.password.create': '비밀번호 생성',
    'login.placeholder.password.confirm': '비밀번호 확인',
    'login.placeholder.password.enter': '비밀번호 입력',
    'login.password.for': '비밀번호',
    'login.error.email': '유효한 이메일을 입력해주세요.',
  },
  en: {
    'nav.map': 'Meister High School Map',
    'nav.creators': 'Creators',
    'nav.traffic': 'Traffic Report',
    'nav.settings': 'Settings',
    'nav.login': 'Login',
    'dashboard.welcome': 'Welcome',
    'login.title.signup': 'Create an account',
    'login.title.login': 'Welcome',
    'login.subtitle.signup': 'Join us and get started.',
    'login.subtitle.login': 'Enter your email to get started.',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.password.confirm': 'Confirm Password',
    'login.password.enter': 'Enter your password',
    'login.button.signup': 'Sign up',
    'login.button.login': 'Log in',
    'login.button.processing': 'Processing...',
    'login.button.letsgo': 'Let\'s go',
    'login.no_account': 'Don\'t have an account?',
    'login.has_account': 'Already have an account?',
    'login.back': 'Back',
    'login.placeholder.email': 'you@example.com',
    'login.placeholder.password.create': 'Create a password',
    'login.placeholder.password.confirm': 'Confirm your password',
    'login.placeholder.password.enter': 'Enter your password',
    'login.password.for': 'Password for',
    'login.error.email': 'Please enter a valid email',
  },
  zh: {
    'nav.map': '迈斯特高中地图',
    'nav.creators': '主创团队',
    'nav.traffic': '流量报告',
    'nav.settings': '设置',
    'nav.login': '登录',
    'dashboard.welcome': '欢迎',
    'login.title.signup': '注册账号',
    'login.title.login': '欢迎回来',
    'login.subtitle.signup': '立即注册并开始。',
    'login.subtitle.login': '输入电子邮箱开始使用。',
    'login.email': '电子邮箱',
    'login.password': '密码',
    'login.password.confirm': '确认密码',
    'login.password.enter': '请输入密码',
    'login.button.signup': '注册',
    'login.button.login': '登录',
    'login.button.processing': '处理中...',
    'login.button.letsgo': '出发',
    'login.no_account': '还没有账号？',
    'login.has_account': '已经有账号了？',
    'login.back': '返回',
    'login.placeholder.email': 'you@example.com',
    'login.placeholder.password.create': '创建密码',
    'login.placeholder.password.confirm': '确认您的密码',
    'login.placeholder.password.enter': '输入您的密码',
    'login.password.for': '密码：',
    'login.error.email': '请输入有效的电子邮箱',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {

  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'ko';
  });

  useEffect(() => {
    const handleStorageChange = () => {
      const saved = localStorage.getItem('language');
      if (saved === 'ko' || saved === 'en') {
        setLanguageState(saved as Language);
      }
    };
    window.addEventListener('storage', handleStorageChange);
    return () => {
      window.removeEventListener('storage', handleStorageChange);
    };
  }, []);

  const setLanguage = (lang: Language) => {
    localStorage.setItem('language', lang);
    setLanguageState(lang);
    window.dispatchEvent(new Event('storage'));
  };

  const t = (keyOrKo: string, fallbackEn?: string) => {
    if (!keyOrKo) return '';
    if (language === 'ko') {
      if ((translations.ko as any)[keyOrKo]) {
        return (translations.ko as any)[keyOrKo];
      }
      return keyOrKo;
    }

    // English mode
    if ((translations.en as any)[keyOrKo]) {
      return (translations.en as any)[keyOrKo];
    }
    if (fallbackEn) {
      return fallbackEn;
    }
    if (koToEnMap[keyOrKo]) {
      return koToEnMap[keyOrKo];
    }

    // Dynamic currency replacement
    if (keyOrKo.endsWith('원')) {
      const numStr = keyOrKo.slice(0, -1);
      if (/^[0-9,]+$/.test(numStr)) {
        return numStr + ' KRW';
      }
    }

    // Dynamic pass rate translation
    if (keyOrKo.includes('필기 약 ') || keyOrKo.includes('실기 약 ') || keyOrKo.includes('필기') || keyOrKo.includes('실기')) {
      let result = keyOrKo;
      result = result.replace(/필기 약 /g, 'Written approx. ');
      result = result.replace(/실기 약 /g, 'Practical approx. ');
      result = result.replace(/필기/g, 'Written');
      result = result.replace(/실기/g, 'Practical');
      result = result.replace(/약 /g, 'approx. ');
      return result;
    }

    return keyOrKo;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export function useLanguage() {
  const context = React.useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
